# Generated by Django 3.2.6 on 2021-10-27 08:18

import datetime
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ajaxsend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('result', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AssetTb',
            fields=[
                ('Ast_Tag_nbr', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Serial_No', models.CharField(blank=True, max_length=100, null=True)),
                ('AstNo', models.CharField(blank=True, max_length=50, null=True)),
                ('Vendor', models.CharField(blank=True, max_length=100, null=True)),
                ('Ast_description', models.CharField(max_length=100, null=True)),
                ('Item_Cost_UGX', models.FloatField(blank=True)),
                ('Item_Cost_USD', models.FloatField(blank=True)),
                ('Asset_Type', models.CharField(blank=True, choices=[('Vehicle', 'Vehicle'), ('Desktop', 'Desktop'), ('Laptop', 'Laptop'), ('Medical Equipment', 'Medical Equipment'), ('Tablet', 'Tablet'), ('Phone', 'Phone'), ('Computer Accessory', 'Computer Accessory'), ('Networking Equipment', 'Networking Equipment'), ('Projector', 'Projector'), ('Printer', 'Printer'), ('PhotoCopier', 'PhotoCopier'), ('Multi Functional Printer', 'Multi Functional Printer'), ('Table', 'Table'), ('Chair', 'Chair'), ('Office Accessory', 'Office Accessory'), ('Fan', 'Fan'), ('Inverter', 'Inverter'), ('Server', 'Server'), ('Firewall', 'Firewall'), ('Safe', 'Safe'), ('Shredder', 'Shredder'), ('Switch', 'Switch'), ('Microwave', 'Microwave'), ('Refrigerator', 'Refrigerator'), ('Network Storage Equipment', 'Network Storage Equipment'), ('Filing Cabinet', 'Filing Cabinet'), ('Trashing Machine', 'Trashing Machine'), ('Drawers', 'Drawers'), ('Fire Extinguisher', 'Fire Extinguisher'), ('Shelf', 'Shelf'), ('Sofa Chairs', 'Sofa Chairs'), ('High Back Rotating Chair', 'High Back Rotating Chair'), ('Low Back Rotating Chair', 'Low Back Rotating Chair'), ('Television', 'Television'), ('Water Dispenser', 'Water Dispenser'), ('Tent', 'Tent'), ('Not Applicable', 'Not Applicable')], max_length=50, null=True)),
                ('Model_No', models.CharField(blank=True, max_length=50, null=True)),
                ('Project', models.CharField(choices=[('P51PPI', 'P51PPI'), ('6002', '6002'), ('3901', '3901'), ('640051', '640051'), ('4499', '4499'), ('4562PERM', '4562PERM'), ('4482UG', '4482UG'), ('351CCP1', '351CCP1'), ('351ICA', '351ICA'), ('51CCP1', '51CCP1'), ('4115WSHTUNZ', '4115WSHTUNZ'), ('85026', '85026'), ('85032', '85032'), ('051E06', '051E06'), ('4562SA', '4562SA'), ('4562PM', '4562PM'), ('4520', '4520'), ('4336P4HVOP', '4336P4HVOP'), ('4519', '4519'), ('4548', '4548'), ('4385Y3', '4385Y3'), ('051E03', '051E03'), ('4560UG', '4560UG'), ('351E03', '351E03'), ('351CCP2', '351CCP2'), ('4565351', '4565351'), ('4628UG', '4628UG'), ('4621UG', '4621UG'), ('3929BNS', '3929BNS'), ('456951', '456951')], max_length=100, null=True)),
                ('Asset_Condition', models.CharField(blank=True, choices=[('New', 'New'), ('Good', 'Good'), ('Fair', 'Fair'), ('Bad', 'Bad'), ('Faulty', 'Faulty'), ('Due for Disposal', 'Due for Disposal'), ('Disposed-Of', 'Disposed-Of'), ('Written Off', 'Written Off')], max_length=100, null=True)),
                ('Asset_Status', models.CharField(choices=[('VERIFIED', 'VERIFIED'), ('UNVERIFIED', 'UNVERIFIED')], max_length=100, null=True)),
                ('Project_Name', models.CharField(choices=[('P51PPI', 'P51PPI'), ('6002', '6002'), ('3901', '3901'), ('640051', '640051'), ('4499', '4499'), ('4562PERM', '4562PERM'), ('4482UG', '4482UG'), ('351CCP1', '351CCP1'), ('351ICA', '351ICA'), ('51CCP1', '51CCP1'), ('4115WSHTUNZ', '4115WSHTUNZ'), ('85026', '85026'), ('85032', '85032'), ('051E06', '051E06'), ('4562SA', '4562SA'), ('4562PM', '4562PM'), ('4520', '4520'), ('4336P4HVOP', '4336P4HVOP'), ('4519', '4519'), ('4548', '4548'), ('4385Y3', '4385Y3'), ('051E03', '051E03'), ('4560UG', '4560UG'), ('351E03', '351E03'), ('351CCP2', '351CCP2'), ('4565351', '4565351'), ('4628UG', '4628UG'), ('4621UG', '4621UG'), ('3929BNS', '3929BNS'), ('456951', '456951')], max_length=100, null=True)),
                ('Availability', models.CharField(blank=True, choices=[('Available', 'Available'), ('Assigned', 'Assigned'), ('To Be Assigned', 'To Be Assigned'), ('Unverified', 'Unverified'), ('Missing', 'Missing'), ('Lost', 'Lost'), ('Insurance', 'Insurance'), ('Not Applicable on this Device', 'Not Applicable on this Device')], max_length=40, null=True)),
                ('Location', models.CharField(blank=True, choices=[('Head Office', 'Head Office'), ('Central Region Office', 'Central Region Office'), ('North Eastern Region Office', 'North Eastern Region Office'), ('Jinja', 'Jinja'), ('Server room', 'Server room'), ('Financial Accounts', 'Financial Accounts'), ("CR's Office", "CR's Office"), ('HR Office', 'HR Office'), ('SIL Office', 'SIL Office'), ('Supply Chain Office', 'Supply Chain Office'), ('IT Office', 'IT Office'), ('Programs Office', 'Programs Office'), ('SMD Office', 'SMD Office')], max_length=40, null=True)),
                ('PurchaseDate', models.DateField(blank=True, default=datetime.datetime(2021, 10, 27, 8, 18, 33, 714661, tzinfo=utc))),
                ('Comments', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ast_Tag_nbr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.assettb', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CsvUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.FileField(upload_to='img')),
                ('Date_uploaded', models.DateTimeField(auto_now_add=True)),
                ('Parsed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PoolRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='staff',
            fields=[
                ('Username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Firstname', models.CharField(max_length=30)),
                ('Lastname', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('profile_pic', models.ImageField(blank=True, default='profile1.png', null=True, upload_to='')),
                ('staffrole', models.CharField(choices=[('User', 'User'), ('Admin', 'Admin'), ('Supervisor', 'Supervisor'), ('Warehouse', 'Warehouse'), ('Supply Chain', 'Supply Chain'), ('SalesApprover', 'SalesApprover'), ('Accountant', 'Accountant'), ('Finance', 'Finance'), ('Assistant Accountant AR', 'Assistant Accountant AR'), ('Systems Administrator', 'Systems Administrator'), ('SIL Officer', 'SIL Officer'), ('Fleet Supervisor', 'Fleet Supervisor')], default=django.contrib.auth.models.User, max_length=30, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Verified',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.CharField(blank=True, default='Unverified', max_length=30)),
                ('Location', models.CharField(blank=True, choices=[('Head Office', 'Head Office'), ('Central Region Office', 'Central Region Office'), ('North Eastern Region Office', 'North Eastern Region Office'), ('Jinja', 'Jinja'), ('Server room', 'Server room'), ('Financial Accounts', 'Financial Accounts'), ("CR's Office", "CR's Office"), ('HR Office', 'HR Office'), ('SIL Office', 'SIL Office'), ('Supply Chain Office', 'Supply Chain Office'), ('IT Office', 'IT Office'), ('Programs Office', 'Programs Office'), ('SMD Office', 'SMD Office')], max_length=40, null=True)),
                ('Comments', models.CharField(blank=True, max_length=1000)),
                ('Ast_Tag_nbr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.assettb')),
                ('Username', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.staff')),
            ],
        ),
        migrations.CreateModel(
            name='UserAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AssignedAsset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.assettb')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.staff')),
            ],
        ),
        migrations.CreateModel(
            name='QRCodeClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QRimage', models.ImageField(blank=True, default='profile1.png', null=True, upload_to='')),
                ('path', models.CharField(max_length=100)),
                ('Asset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.assettb')),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EventType', models.CharField(choices=[('Asset Addition', 'Asset Addition'), ('Asset Modification', 'Asset Modification'), ('Asset Deletion', 'Asset Deletion'), ('Asset Request', 'Asset Request'), ('Asset Assignment', 'Asset Assignment'), ('Account Created', 'Account Created'), ('Login Event', 'Login Event'), ('Failed Login Event', 'Failed Login Event'), ('Login Event', 'Login Event'), ('Logout Event', 'Logout Event')], max_length=30)),
                ('EventSummary', models.CharField(blank=True, max_length=1000, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Disposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disposalDate', models.DateField(auto_now_add=True)),
                ('disposalIncome', models.FloatField()),
                ('disposalProcedure', models.CharField(choices=[('Donated', 'Donated'), ('Sold', 'Sold')], max_length=30)),
                ('disposalExplanation', models.BooleanField(default=False)),
                ('comments', models.CharField(blank=True, max_length=1000, null=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.assettb')),
            ],
        ),
        migrations.CreateModel(
            name='DeleteAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Response', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('Comments', models.CharField(blank=True, max_length=200, null=True)),
                ('AssignmentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.assignment')),
            ],
        ),
        migrations.CreateModel(
            name='ChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AstTagnbr', models.CharField(max_length=100, null=True)),
                ('SerialNo', models.CharField(blank=True, max_length=100, null=True)),
                ('AstNo', models.CharField(blank=True, max_length=50, null=True)),
                ('Vendor', models.CharField(blank=True, max_length=100, null=True)),
                ('AstDescription', models.CharField(max_length=100, null=True)),
                ('ItemCostUGX', models.FloatField(blank=True, null=True)),
                ('ItemCostUSD', models.FloatField(blank=True, null=True)),
                ('AssetType', models.CharField(blank=True, choices=[('Vehicle', 'Vehicle'), ('Desktop', 'Desktop'), ('Laptop', 'Laptop'), ('Medical Equipment', 'Medical Equipment'), ('Tablet', 'Tablet'), ('Phone', 'Phone'), ('Computer Accessory', 'Computer Accessory'), ('Networking Equipment', 'Networking Equipment'), ('Projector', 'Projector'), ('Printer', 'Printer'), ('PhotoCopier', 'PhotoCopier'), ('Multi Functional Printer', 'Multi Functional Printer'), ('Table', 'Table'), ('Chair', 'Chair'), ('Office Accessory', 'Office Accessory'), ('Fan', 'Fan'), ('Inverter', 'Inverter'), ('Server', 'Server'), ('Firewall', 'Firewall'), ('Safe', 'Safe'), ('Shredder', 'Shredder'), ('Switch', 'Switch'), ('Microwave', 'Microwave'), ('Refrigerator', 'Refrigerator'), ('Network Storage Equipment', 'Network Storage Equipment'), ('Filing Cabinet', 'Filing Cabinet'), ('Trashing Machine', 'Trashing Machine'), ('Drawers', 'Drawers'), ('Fire Extinguisher', 'Fire Extinguisher'), ('Shelf', 'Shelf'), ('Sofa Chairs', 'Sofa Chairs'), ('High Back Rotating Chair', 'High Back Rotating Chair'), ('Low Back Rotating Chair', 'Low Back Rotating Chair'), ('Television', 'Television'), ('Water Dispenser', 'Water Dispenser'), ('Tent', 'Tent'), ('Not Applicable', 'Not Applicable')], max_length=50, null=True)),
                ('ModelNo', models.CharField(blank=True, max_length=50, null=True)),
                ('Project', models.CharField(blank=True, choices=[('P51PPI', 'P51PPI'), ('6002', '6002'), ('3901', '3901'), ('640051', '640051'), ('4499', '4499'), ('4562PERM', '4562PERM'), ('4482UG', '4482UG'), ('351CCP1', '351CCP1'), ('351ICA', '351ICA'), ('51CCP1', '51CCP1'), ('4115WSHTUNZ', '4115WSHTUNZ'), ('85026', '85026'), ('85032', '85032'), ('051E06', '051E06'), ('4562SA', '4562SA'), ('4562PM', '4562PM'), ('4520', '4520'), ('4336P4HVOP', '4336P4HVOP'), ('4519', '4519'), ('4548', '4548'), ('4385Y3', '4385Y3'), ('051E03', '051E03'), ('4560UG', '4560UG'), ('351E03', '351E03'), ('351CCP2', '351CCP2'), ('4565351', '4565351'), ('4628UG', '4628UG'), ('4621UG', '4621UG'), ('3929BNS', '3929BNS'), ('456951', '456951')], max_length=100, null=True)),
                ('AssetCondition', models.CharField(blank=True, choices=[('New', 'New'), ('Good', 'Good'), ('Fair', 'Fair'), ('Bad', 'Bad'), ('Faulty', 'Faulty'), ('Due for Disposal', 'Due for Disposal'), ('Disposed-Of', 'Disposed-Of'), ('Written Off', 'Written Off')], max_length=100, null=True)),
                ('AssetStatus', models.CharField(blank=True, choices=[('VERIFIED', 'VERIFIED'), ('UNVERIFIED', 'UNVERIFIED')], max_length=100, null=True)),
                ('ProjectName', models.CharField(blank=True, choices=[('P51PPI', 'P51PPI'), ('6002', '6002'), ('3901', '3901'), ('640051', '640051'), ('4499', '4499'), ('4562PERM', '4562PERM'), ('4482UG', '4482UG'), ('351CCP1', '351CCP1'), ('351ICA', '351ICA'), ('51CCP1', '51CCP1'), ('4115WSHTUNZ', '4115WSHTUNZ'), ('85026', '85026'), ('85032', '85032'), ('051E06', '051E06'), ('4562SA', '4562SA'), ('4562PM', '4562PM'), ('4520', '4520'), ('4336P4HVOP', '4336P4HVOP'), ('4519', '4519'), ('4548', '4548'), ('4385Y3', '4385Y3'), ('051E03', '051E03'), ('4560UG', '4560UG'), ('351E03', '351E03'), ('351CCP2', '351CCP2'), ('4565351', '4565351'), ('4628UG', '4628UG'), ('4621UG', '4621UG'), ('3929BNS', '3929BNS'), ('456951', '456951')], max_length=100, null=True)),
                ('Availability', models.CharField(blank=True, choices=[('Available', 'Available'), ('Assigned', 'Assigned'), ('To Be Assigned', 'To Be Assigned'), ('Unverified', 'Unverified'), ('Missing', 'Missing'), ('Lost', 'Lost'), ('Insurance', 'Insurance'), ('Not Applicable on this Device', 'Not Applicable on this Device')], max_length=40, null=True)),
                ('Location', models.CharField(blank=True, choices=[('Head Office', 'Head Office'), ('Central Region Office', 'Central Region Office'), ('North Eastern Region Office', 'North Eastern Region Office'), ('Jinja', 'Jinja'), ('Server room', 'Server room'), ('Financial Accounts', 'Financial Accounts'), ("CR's Office", "CR's Office"), ('HR Office', 'HR Office'), ('SIL Office', 'SIL Office'), ('Supply Chain Office', 'Supply Chain Office'), ('IT Office', 'IT Office'), ('Programs Office', 'Programs Office'), ('SMD Office', 'SMD Office')], max_length=40, null=True)),
                ('PurchaseDate', models.DateField(blank=True, default=datetime.datetime(2021, 10, 27, 8, 18, 33, 718062, tzinfo=utc))),
                ('Modifications', models.CharField(blank=True, max_length=2000, null=True)),
                ('RequesterComments', models.CharField(blank=True, max_length=1000, null=True)),
                ('FAMApproval', models.CharField(blank=True, choices=[('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=15, null=True)),
                ('FAMApprovalComments', models.CharField(blank=True, max_length=100, null=True)),
                ('LogDate', models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 27, 8, 18, 33, 718111, tzinfo=utc))),
                ('Requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='assignment',
            name='Username',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.staff'),
        ),
        migrations.CreateModel(
            name='AssetRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Device_Type', models.CharField(blank=True, choices=[('Vehicle', 'Vehicle'), ('Desktop', 'Desktop'), ('Laptop', 'Laptop'), ('Medical Equipment', 'Medical Equipment'), ('Tablet', 'Tablet'), ('Phone', 'Phone'), ('Computer Accessory', 'Computer Accessory'), ('Networking Equipment', 'Networking Equipment'), ('Projector', 'Projector'), ('Printer', 'Printer'), ('PhotoCopier', 'PhotoCopier'), ('Multi Functional Printer', 'Multi Functional Printer'), ('Table', 'Table'), ('Chair', 'Chair'), ('Office Accessory', 'Office Accessory'), ('Fan', 'Fan'), ('Inverter', 'Inverter'), ('Server', 'Server'), ('Firewall', 'Firewall'), ('Safe', 'Safe'), ('Shredder', 'Shredder'), ('Switch', 'Switch'), ('Microwave', 'Microwave'), ('Refrigerator', 'Refrigerator'), ('Network Storage Equipment', 'Network Storage Equipment'), ('Filing Cabinet', 'Filing Cabinet'), ('Trashing Machine', 'Trashing Machine'), ('Drawers', 'Drawers'), ('Fire Extinguisher', 'Fire Extinguisher'), ('Shelf', 'Shelf'), ('Sofa Chairs', 'Sofa Chairs'), ('High Back Rotating Chair', 'High Back Rotating Chair'), ('Low Back Rotating Chair', 'Low Back Rotating Chair'), ('Television', 'Television'), ('Water Dispenser', 'Water Dispenser'), ('Tent', 'Tent'), ('Not Applicable', 'Not Applicable')], max_length=50, null=True)),
                ('Status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('User Accepted', 'User Accepted'), ('Returned', 'Returned')], default='Pending', max_length=50, null=True)),
                ('Date_Requested', models.DateField(default=datetime.datetime(2021, 10, 27, 8, 18, 33, 715045, tzinfo=utc))),
                ('Reason', models.TextField(blank=True, max_length=1500, null=True)),
                ('Request_Modified_Date', models.DateField(default=datetime.datetime(2021, 10, 27, 8, 18, 33, 715069, tzinfo=utc))),
                ('Last_Modified', models.DateField(default=datetime.datetime(2021, 10, 27, 8, 18, 33, 715094, tzinfo=utc))),
                ('Last_Modified_by', models.CharField(blank=True, max_length=500)),
                ('SupervisorApproval', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('User Accepted', 'User Accepted'), ('Returned', 'Returned')], default='Pending', max_length=15, null=True)),
                ('SupervisorApprovalComments', models.CharField(blank=True, max_length=1000, null=True)),
                ('AssetManagerApproval', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('User Accepted', 'User Accepted'), ('Returned', 'Returned')], default='Pending', max_length=15, null=True)),
                ('AssetMangerApprovalComments', models.CharField(blank=True, max_length=1000, null=True)),
                ('FinanceManagerApproval', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('User Accepted', 'User Accepted'), ('Returned', 'Returned')], default='Pending', max_length=15, null=True)),
                ('FinanceManagerApprovalComments', models.CharField(blank=True, max_length=1000, null=True)),
                ('UserAcceptance', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('User Accepted', 'User Accepted'), ('Returned', 'Returned')], default='Pending', max_length=15, null=True)),
                ('Assigned_Device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.assettb')),
                ('Username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.staff')),
            ],
        ),
    ]
