# Generated by Django 3.2.6 on 2021-10-28 03:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20211027_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='EventDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 28, 3, 4, 5, 981819, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='events',
            name='EventObject',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assetrequests',
            name='Date_Requested',
            field=models.DateField(default=datetime.datetime(2021, 10, 28, 3, 4, 5, 977293, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='assetrequests',
            name='Last_Modified',
            field=models.DateField(default=datetime.datetime(2021, 10, 28, 3, 4, 5, 977339, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='assetrequests',
            name='Request_Modified_Date',
            field=models.DateField(default=datetime.datetime(2021, 10, 28, 3, 4, 5, 977316, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='assettb',
            name='PurchaseDate',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 10, 28, 3, 4, 5, 976876, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='LogDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 28, 3, 4, 5, 980832, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='PurchaseDate',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 10, 28, 3, 4, 5, 980785, tzinfo=utc)),
        ),
    ]
