# Generated by Django 3.2.6 on 2021-10-29 07:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20211028_0905'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='Ast_Tag_nbr',
            new_name='ast_tag_nbr',
        ),
        migrations.RenameField(
            model_name='assignment',
            old_name='Username',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='assetrequests',
            name='Date_Requested',
            field=models.DateField(default=datetime.datetime(2021, 10, 29, 7, 14, 55, 243743, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='assetrequests',
            name='Last_Modified',
            field=models.DateField(default=datetime.datetime(2021, 10, 29, 7, 14, 55, 243793, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='assetrequests',
            name='Request_Modified_Date',
            field=models.DateField(default=datetime.datetime(2021, 10, 29, 7, 14, 55, 243779, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='assettb',
            name='PurchaseDate',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 10, 29, 7, 14, 55, 243191, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='LogDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 29, 7, 14, 55, 247670, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='PurchaseDate',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 10, 29, 7, 14, 55, 247622, tzinfo=utc)),
        ),
    ]
