# Generated by Django 3.2.6 on 2021-10-29 11:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20211029_0715'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='ast_tag_nbr',
            new_name='Ast_Tag_nbr',
        ),
        migrations.RenameField(
            model_name='assignment',
            old_name='username',
            new_name='Username',
        ),
        migrations.AlterField(
            model_name='assetrequests',
            name='Date_Requested',
            field=models.DateField(default=datetime.datetime(2021, 10, 29, 11, 44, 46, 211109, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='assetrequests',
            name='Last_Modified',
            field=models.DateField(default=datetime.datetime(2021, 10, 29, 11, 44, 46, 211142, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='assetrequests',
            name='Request_Modified_Date',
            field=models.DateField(default=datetime.datetime(2021, 10, 29, 11, 44, 46, 211132, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='assettb',
            name='PurchaseDate',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 10, 29, 11, 44, 46, 210673, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='LogDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 29, 11, 44, 46, 214155, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='PurchaseDate',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 10, 29, 11, 44, 46, 214106, tzinfo=utc)),
        ),
    ]
