# Generated by Django 3.2.6 on 2021-11-03 05:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20211103_0315'),
    ]

    operations = [
        migrations.AddField(
            model_name='disposal',
            name='CR_Approval',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('User Accepted', 'User Accepted'), ('Returned', 'Returned')], default='Pending', max_length=30),
        ),
        migrations.AddField(
            model_name='disposal',
            name='fairMarketValue',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assetrequests',
            name='Date_Requested',
            field=models.DateField(default=datetime.datetime(2021, 11, 3, 5, 21, 38, 679491, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='assetrequests',
            name='Last_Modified',
            field=models.DateField(default=datetime.datetime(2021, 11, 3, 5, 21, 38, 679523, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='assetrequests',
            name='Request_Modified_Date',
            field=models.DateField(default=datetime.datetime(2021, 11, 3, 5, 21, 38, 679513, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='assettb',
            name='Asset_Condition',
            field=models.CharField(blank=True, choices=[('New', 'New'), ('Good', 'Good'), ('Fair', 'Fair'), ('Bad', 'Bad'), ('Faulty', 'Faulty')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assettb',
            name='Asset_Status',
            field=models.CharField(choices=[('VERIFIED', 'VERIFIED'), ('UNVERIFIED', 'UNVERIFIED'), ('LOST', 'LOST'), ('AUCTIONED', 'AUCTIONED')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assettb',
            name='Availability',
            field=models.CharField(blank=True, choices=[('Available', 'Available'), ('Assigned', 'Assigned'), ('To Be Assigned', 'To Be Assigned'), ('Unavailable for Assignment', 'Unavailable for Assignment'), ('Missing', 'Missing'), ('Lost', 'Lost'), ('Faulty-Due For Disposal', 'Faulty-Due For Disposal'), ('Due for Disposal', 'Due for Disposal'), ('Disposed-Of', 'Disposed-Of'), ('Written Off', 'Written Off'), ('For Insurance Replacement', 'For Insurance Replacement'), ('Not Applicable on this Device', 'Not Applicable on this Device')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='assettb',
            name='PurchaseDate',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 11, 3, 5, 21, 38, 679102, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='AssetCondition',
            field=models.CharField(blank=True, choices=[('New', 'New'), ('Good', 'Good'), ('Fair', 'Fair'), ('Bad', 'Bad'), ('Faulty', 'Faulty')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='AssetStatus',
            field=models.CharField(blank=True, choices=[('VERIFIED', 'VERIFIED'), ('UNVERIFIED', 'UNVERIFIED'), ('LOST', 'LOST'), ('AUCTIONED', 'AUCTIONED')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='Availability',
            field=models.CharField(blank=True, choices=[('Available', 'Available'), ('Assigned', 'Assigned'), ('To Be Assigned', 'To Be Assigned'), ('Unavailable for Assignment', 'Unavailable for Assignment'), ('Missing', 'Missing'), ('Lost', 'Lost'), ('Faulty-Due For Disposal', 'Faulty-Due For Disposal'), ('Due for Disposal', 'Due for Disposal'), ('Disposed-Of', 'Disposed-Of'), ('Written Off', 'Written Off'), ('For Insurance Replacement', 'For Insurance Replacement'), ('Not Applicable on this Device', 'Not Applicable on this Device')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='LogDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 11, 3, 5, 21, 38, 682512, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='PurchaseDate',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 11, 3, 5, 21, 38, 682467, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='disposal',
            name='disposalDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='disposal',
            name='disposalExplanation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='disposal',
            name='disposalProcedure',
            field=models.CharField(choices=[('Donated', 'Donated'), ('Sold', 'Sold'), ('Auctioned', 'Auctioned'), ('Written-Off', 'Written-off')], max_length=30),
        ),
    ]
