# Generated by Django 3.2.6 on 2021-11-12 03:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_auto_20211103_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='disposal',
            name='Buyer',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='disposal',
            name='CheckedOut',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='disposal',
            name='Paymentmode',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Salary Deduction', 'Salary Deduction')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='assetrequests',
            name='Date_Requested',
            field=models.DateField(default=datetime.datetime(2021, 11, 12, 3, 22, 6, 516211, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='assetrequests',
            name='Last_Modified',
            field=models.DateField(default=datetime.datetime(2021, 11, 12, 3, 22, 6, 516263, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='assetrequests',
            name='Request_Modified_Date',
            field=models.DateField(default=datetime.datetime(2021, 11, 12, 3, 22, 6, 516252, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='assettb',
            name='Location',
            field=models.CharField(blank=True, choices=[('Head Office', 'Head Office'), ('Central Region Office', 'Central Region Office'), ('North Eastern Region Office', 'North Eastern Region Office'), ('Jinja', 'Jinja'), ('Server room', 'Server room'), ('Financial Accounts', 'Financial Accounts'), ("CR's Office", "CR's Office"), ('HR Office', 'HR Office'), ('SIL Office', 'SIL Office'), ('Supply Chain Office', 'Supply Chain Office'), ('IT Office', 'IT Office'), ('Programs Office', 'Programs Office'), ('SMD Office', 'SMD Office'), ('HQ-COMMON AREA', 'HQ-COMMON AREA'), ('RECEPTION-HEAD OFFICE', 'RECEPTION-HEAD OFFICE'), ('CAFETERIA', 'CAFETERIA'), ('EASTERN REGION OFFICE', 'EASTERN REGION OFFICE'), ('NORTHERN REGION OFFICE', 'NORTHERN REGION OFFICE'), ('NORTH EASTERN REGION OFFICE-JINJA', 'NORTH EASTERN REGION OFFICE-JINJA'), ('NORTH EASTERN REGION OFFICE-MBALE', 'NORTH EASTERN REGION OFFICE-MBALE'), ('BOARDROOM', 'BOARDROOM'), ('FINANCIAL ANALYTICS OFFICE', 'FINANCIAL ANALYTICS OFFICE'), ('DIRECTOR ADMIN AND FINANCE', 'DIRECTOR ADMIN AND FINANCE'), ('DIRECTOR PROGRAMS', 'DIRECTOR PROGRAMS'), ('KCCA MANE OFFICE', 'KCCA MANE OFFICE'), ('DEPUTY COUNTRY REPS OFFICE', 'DEPUTY COUNTRY REPS OFFICE'), ('DISC', 'DISC'), ('DIRECTOR WHP', 'DIRECTOR WHP')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='assettb',
            name='Project',
            field=models.CharField(choices=[('P51PPI', 'P51PPI'), ('6002', '6002'), ('3901', '3901'), ('640051', '640051'), ('4499', '4499'), ('4562PERM', '4562PERM'), ('4482UG', '4482UG'), ('351CCP1', '351CCP1'), ('351ICA', '351ICA'), ('51CCP1', '51CCP1'), ('4115WSHTUNZ', '4115WSHTUNZ'), ('85026', '85026'), ('85032', '85032'), ('051E06', '051E06'), ('4562SA', '4562SA'), ('4562PM', '4562PM'), ('4520', '4520'), ('4336P4HVOP', '4336P4HVOP'), ('4519', '4519'), ('4548', '4548'), ('4385Y3', '4385Y3'), ('051E03', '051E03'), ('4560UG', '4560UG'), ('351E03', '351E03'), ('351CCP2', '351CCP2'), ('4565351', '4565351'), ('4628UG', '4628UG'), ('4621UG', '4621UG'), ('3929BNS', '3929BNS'), ('456951', '456951'), ('3646Y', '3646Y'), ('610051', '610051'), ('630051', '630051'), ('3526', '3526'), ('P3111', 'P3111'), ('P2490', 'P2490'), ('3706SUB', '3706SUB'), ('4254', '4254')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assettb',
            name='Project_Name',
            field=models.CharField(choices=[('WHP', 'WHP'), ('MERCK', 'MERCK'), ('MUM', 'MUM'), ('PFIZER', 'PFIZER'), ('PROGRAM INCOME', 'PROGRAM INCOME'), ('MANE', 'MANE'), ('CMS PROJECT', 'CMS PROJECT'), ('TUNZA', 'TUNZA'), ('COMMERCIAL MARKETS', 'COMMERCIAL MARKETS'), ('CM4FP', 'CM4FP'), ('BERGSTROM FOUNDATION', 'BERGSTROM FOUNDATION'), ('DISC', 'DISC'), ('COMMON COST', 'COMMON COST'), ('HIVST', 'HIVST'), ('CDC', 'CDC'), ('CSF', 'CSF'), ('WIN', 'WIN')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assettb',
            name='PurchaseDate',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 11, 12, 3, 22, 6, 515493, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='Location',
            field=models.CharField(blank=True, choices=[('Head Office', 'Head Office'), ('Central Region Office', 'Central Region Office'), ('North Eastern Region Office', 'North Eastern Region Office'), ('Jinja', 'Jinja'), ('Server room', 'Server room'), ('Financial Accounts', 'Financial Accounts'), ("CR's Office", "CR's Office"), ('HR Office', 'HR Office'), ('SIL Office', 'SIL Office'), ('Supply Chain Office', 'Supply Chain Office'), ('IT Office', 'IT Office'), ('Programs Office', 'Programs Office'), ('SMD Office', 'SMD Office'), ('HQ-COMMON AREA', 'HQ-COMMON AREA'), ('RECEPTION-HEAD OFFICE', 'RECEPTION-HEAD OFFICE'), ('CAFETERIA', 'CAFETERIA'), ('EASTERN REGION OFFICE', 'EASTERN REGION OFFICE'), ('NORTHERN REGION OFFICE', 'NORTHERN REGION OFFICE'), ('NORTH EASTERN REGION OFFICE-JINJA', 'NORTH EASTERN REGION OFFICE-JINJA'), ('NORTH EASTERN REGION OFFICE-MBALE', 'NORTH EASTERN REGION OFFICE-MBALE'), ('BOARDROOM', 'BOARDROOM'), ('FINANCIAL ANALYTICS OFFICE', 'FINANCIAL ANALYTICS OFFICE'), ('DIRECTOR ADMIN AND FINANCE', 'DIRECTOR ADMIN AND FINANCE'), ('DIRECTOR PROGRAMS', 'DIRECTOR PROGRAMS'), ('KCCA MANE OFFICE', 'KCCA MANE OFFICE'), ('DEPUTY COUNTRY REPS OFFICE', 'DEPUTY COUNTRY REPS OFFICE'), ('DISC', 'DISC'), ('DIRECTOR WHP', 'DIRECTOR WHP')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='LogDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 11, 12, 3, 22, 6, 520300, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='Project',
            field=models.CharField(blank=True, choices=[('P51PPI', 'P51PPI'), ('6002', '6002'), ('3901', '3901'), ('640051', '640051'), ('4499', '4499'), ('4562PERM', '4562PERM'), ('4482UG', '4482UG'), ('351CCP1', '351CCP1'), ('351ICA', '351ICA'), ('51CCP1', '51CCP1'), ('4115WSHTUNZ', '4115WSHTUNZ'), ('85026', '85026'), ('85032', '85032'), ('051E06', '051E06'), ('4562SA', '4562SA'), ('4562PM', '4562PM'), ('4520', '4520'), ('4336P4HVOP', '4336P4HVOP'), ('4519', '4519'), ('4548', '4548'), ('4385Y3', '4385Y3'), ('051E03', '051E03'), ('4560UG', '4560UG'), ('351E03', '351E03'), ('351CCP2', '351CCP2'), ('4565351', '4565351'), ('4628UG', '4628UG'), ('4621UG', '4621UG'), ('3929BNS', '3929BNS'), ('456951', '456951'), ('3646Y', '3646Y'), ('610051', '610051'), ('630051', '630051'), ('3526', '3526'), ('P3111', 'P3111'), ('P2490', 'P2490'), ('3706SUB', '3706SUB'), ('4254', '4254')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='ProjectName',
            field=models.CharField(blank=True, choices=[('P51PPI', 'P51PPI'), ('6002', '6002'), ('3901', '3901'), ('640051', '640051'), ('4499', '4499'), ('4562PERM', '4562PERM'), ('4482UG', '4482UG'), ('351CCP1', '351CCP1'), ('351ICA', '351ICA'), ('51CCP1', '51CCP1'), ('4115WSHTUNZ', '4115WSHTUNZ'), ('85026', '85026'), ('85032', '85032'), ('051E06', '051E06'), ('4562SA', '4562SA'), ('4562PM', '4562PM'), ('4520', '4520'), ('4336P4HVOP', '4336P4HVOP'), ('4519', '4519'), ('4548', '4548'), ('4385Y3', '4385Y3'), ('051E03', '051E03'), ('4560UG', '4560UG'), ('351E03', '351E03'), ('351CCP2', '351CCP2'), ('4565351', '4565351'), ('4628UG', '4628UG'), ('4621UG', '4621UG'), ('3929BNS', '3929BNS'), ('456951', '456951'), ('3646Y', '3646Y'), ('610051', '610051'), ('630051', '630051'), ('3526', '3526'), ('P3111', 'P3111'), ('P2490', 'P2490'), ('3706SUB', '3706SUB'), ('4254', '4254')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='PurchaseDate',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 11, 12, 3, 22, 6, 520252, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='verified',
            name='Location',
            field=models.CharField(blank=True, choices=[('Head Office', 'Head Office'), ('Central Region Office', 'Central Region Office'), ('North Eastern Region Office', 'North Eastern Region Office'), ('Jinja', 'Jinja'), ('Server room', 'Server room'), ('Financial Accounts', 'Financial Accounts'), ("CR's Office", "CR's Office"), ('HR Office', 'HR Office'), ('SIL Office', 'SIL Office'), ('Supply Chain Office', 'Supply Chain Office'), ('IT Office', 'IT Office'), ('Programs Office', 'Programs Office'), ('SMD Office', 'SMD Office'), ('HQ-COMMON AREA', 'HQ-COMMON AREA'), ('RECEPTION-HEAD OFFICE', 'RECEPTION-HEAD OFFICE'), ('CAFETERIA', 'CAFETERIA'), ('EASTERN REGION OFFICE', 'EASTERN REGION OFFICE'), ('NORTHERN REGION OFFICE', 'NORTHERN REGION OFFICE'), ('NORTH EASTERN REGION OFFICE-JINJA', 'NORTH EASTERN REGION OFFICE-JINJA'), ('NORTH EASTERN REGION OFFICE-MBALE', 'NORTH EASTERN REGION OFFICE-MBALE'), ('BOARDROOM', 'BOARDROOM'), ('FINANCIAL ANALYTICS OFFICE', 'FINANCIAL ANALYTICS OFFICE'), ('DIRECTOR ADMIN AND FINANCE', 'DIRECTOR ADMIN AND FINANCE'), ('DIRECTOR PROGRAMS', 'DIRECTOR PROGRAMS'), ('KCCA MANE OFFICE', 'KCCA MANE OFFICE'), ('DEPUTY COUNTRY REPS OFFICE', 'DEPUTY COUNTRY REPS OFFICE'), ('DISC', 'DISC'), ('DIRECTOR WHP', 'DIRECTOR WHP')], max_length=40, null=True),
        ),
    ]
