# Generated by Django 3.2.6 on 2021-11-28 02:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_auto_20211127_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetrequests',
            name='Date_Requested',
            field=models.DateField(default=datetime.datetime(2021, 11, 28, 2, 36, 53, 633086, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='assetrequests',
            name='Last_Modified',
            field=models.DateField(default=datetime.datetime(2021, 11, 28, 2, 36, 53, 633121, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='assetrequests',
            name='Request_Modified_Date',
            field=models.DateField(default=datetime.datetime(2021, 11, 28, 2, 36, 53, 633110, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='assettb',
            name='PurchaseDate',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 11, 28, 2, 36, 53, 632619, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='LogDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 11, 28, 2, 36, 53, 636190, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='PurchaseDate',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 11, 28, 2, 36, 53, 636143, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='disposal',
            name='Paymentmode',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Salary Deduction', 'Salary Deduction'), ('Donated', 'Donation')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='disposal',
            name='disposalDate',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 11, 28, 2, 36, 53, 636661, tzinfo=utc)),
        ),
    ]
