# Generated by Django 3.2.6 on 2021-12-14 06:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_auto_20211128_0236'),
    ]

    operations = [
        migrations.AddField(
            model_name='assettb',
            name='Blank_Column',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assettb',
            name='Company',
            field=models.CharField(default=351, max_length=10),
        ),
        migrations.AlterField(
            model_name='assetrequests',
            name='Date_Requested',
            field=models.DateField(default=datetime.datetime(2021, 12, 14, 6, 40, 20, 180168, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='assetrequests',
            name='Device_Type',
            field=models.CharField(blank=True, choices=[('VEHICLE', 'VEHICLE'), ('DESKTOP', 'DESKTOP'), ('LAPTOP', 'LAPTOP'), ('MEDICAL EQUIPMENT', 'MEDICAL EQUIPMENT'), ('TABLET', 'TABLET'), ('PHONE', 'PHONE'), ('COMPUTER ACCESSORY', 'COMPUTER ACCESSORY'), ('NETWORKING EQUIPMENT', 'NETWORKING EQUIPMENT'), ('PROJECTOR', 'PROJECTOR'), ('PRINTER', 'PRINTER'), ('PHOTOCOPIER', 'PHOTOCOPIER'), ('MULTI FUNCTIONAL PRINTER', 'MULTI FUNCTIONAL PRINTER'), ('TABLE', 'TABLE'), ('CHAIR', 'CHAIR'), ('OFFICE ACCESSORY', 'OFFICE ACCESSORY'), ('FAN', 'FAN'), ('INVERTER', 'INVERTER'), ('SERVER', 'SERVER'), ('FIREWALL', 'FIREWALL'), ('SAFE', 'SAFE'), ('SHREDDER', 'SHREDDER'), ('SWITCH', 'SWITCH'), ('BOOKSHELF', 'BOOKSHELF'), ('MICROWAVE', 'MICROWAVE'), ('REFRIGERATOR', 'REFRIGERATOR'), ('NETWORK STORAGE EQUIPMENT', 'NETWORK STORAGE EQUIPMENT'), ('FILING CABINET', 'FILING CABINET'), ('TRASHING MACHINE', 'TRASHING MACHINE'), ('DRAWERS', 'DRAWERS'), ('FIRE EXTINGUISHER', 'FIRE EXTINGUISHER'), ('SHELF', 'SHELF'), ('SOFA CHAIRS', 'SOFA CHAIRS'), ('HIGH BACK ROTATING CHAIR', 'HIGH BACK ROTATING CHAIR'), ('LOW BACK ROTATING CHAIR', 'LOW BACK ROTATING CHAIR'), ('TELEVISION', 'TELEVISION'), ('WATER DISPENSER', 'WATER DISPENSER'), ('TENT', 'TENT'), ('NOT APPLICABLE', 'NOT APPLICABLE')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='assetrequests',
            name='Last_Modified',
            field=models.DateField(default=datetime.datetime(2021, 12, 14, 6, 40, 20, 180203, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='assetrequests',
            name='Request_Modified_Date',
            field=models.DateField(default=datetime.datetime(2021, 12, 14, 6, 40, 20, 180193, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='assettb',
            name='Asset_Type',
            field=models.CharField(blank=True, choices=[('VEHICLE', 'VEHICLE'), ('DESKTOP', 'DESKTOP'), ('LAPTOP', 'LAPTOP'), ('MEDICAL EQUIPMENT', 'MEDICAL EQUIPMENT'), ('TABLET', 'TABLET'), ('PHONE', 'PHONE'), ('COMPUTER ACCESSORY', 'COMPUTER ACCESSORY'), ('NETWORKING EQUIPMENT', 'NETWORKING EQUIPMENT'), ('PROJECTOR', 'PROJECTOR'), ('PRINTER', 'PRINTER'), ('PHOTOCOPIER', 'PHOTOCOPIER'), ('MULTI FUNCTIONAL PRINTER', 'MULTI FUNCTIONAL PRINTER'), ('TABLE', 'TABLE'), ('CHAIR', 'CHAIR'), ('OFFICE ACCESSORY', 'OFFICE ACCESSORY'), ('FAN', 'FAN'), ('INVERTER', 'INVERTER'), ('SERVER', 'SERVER'), ('FIREWALL', 'FIREWALL'), ('SAFE', 'SAFE'), ('SHREDDER', 'SHREDDER'), ('SWITCH', 'SWITCH'), ('BOOKSHELF', 'BOOKSHELF'), ('MICROWAVE', 'MICROWAVE'), ('REFRIGERATOR', 'REFRIGERATOR'), ('NETWORK STORAGE EQUIPMENT', 'NETWORK STORAGE EQUIPMENT'), ('FILING CABINET', 'FILING CABINET'), ('TRASHING MACHINE', 'TRASHING MACHINE'), ('DRAWERS', 'DRAWERS'), ('FIRE EXTINGUISHER', 'FIRE EXTINGUISHER'), ('SHELF', 'SHELF'), ('SOFA CHAIRS', 'SOFA CHAIRS'), ('HIGH BACK ROTATING CHAIR', 'HIGH BACK ROTATING CHAIR'), ('LOW BACK ROTATING CHAIR', 'LOW BACK ROTATING CHAIR'), ('TELEVISION', 'TELEVISION'), ('WATER DISPENSER', 'WATER DISPENSER'), ('TENT', 'TENT'), ('NOT APPLICABLE', 'NOT APPLICABLE')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='assettb',
            name='Availability',
            field=models.CharField(blank=True, choices=[('AVAILABLE', 'AVAILABLE'), ('ASSIGNED', 'ASSIGNED'), ('TO BE ASSIGNED', 'TO BE ASSIGNED'), ('UNAVAILABLE FOR ASSIGNMENT', 'UNAVAILABLE FOR ASSIGNMENT'), ('MISSING', 'MISSING'), ('LOST', 'LOST'), ('FAULTY-DUE FOR DISPOSAL', 'FAULTY-DUE FOR DISPOSAL'), ('DUE FOR DISPOSAL', 'DUE FOR DISPOSAL'), ('DISPOSED-OF', 'DISPOSED-OF'), ('WRITTEN OFF', 'WRITTEN OFF'), ('FOR INSURANCE REPLACEMENT', 'FOR INSURANCE REPLACEMENT'), ('NOT APPLICABLE ON THIS DEVICE', 'NOT APPLICABLE ON THIS DEVICE')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='assettb',
            name='Location',
            field=models.CharField(blank=True, choices=[('HEAD OFFICE', 'HEAD OFFICE'), ('CENTRAL REGION OFFICE', 'CENTRAL REGION OFFICE'), ('NORTH EASTERN REGION OFFICE', 'NORTH EASTERN REGION OFFICE'), ('JINJA', 'JINJA'), ('SERVER ROOM', 'SERVER ROOM'), ('FINANCIAL ACCOUNTS', 'FINANCIAL ACCOUNTS'), ("CR'S OFFICE", "CR'S OFFICE"), ('HR OFFICE', 'HR OFFICE'), ('SIL OFFICE', 'SIL OFFICE'), ('SUPPLY CHAIN OFFICE', 'SUPPLY CHAIN OFFICE'), ('IT OFFICE', 'IT OFFICE'), ('PROGRAMS OFFICE', 'PROGRAMS OFFICE'), ('SMD OFFICE', 'SMD OFFICE'), ('HQ-COMMON AREA', 'HQ-COMMON AREA'), ('RECEPTION-HEAD OFFICE', 'RECEPTION-HEAD OFFICE'), ('CAFETERIA', 'CAFETERIA'), ('EASTERN REGION OFFICE', 'EASTERN REGION OFFICE'), ('NORTHERN REGION OFFICE', 'NORTHERN REGION OFFICE'), ('NORTH EASTERN REGION OFFICE-JINJA', 'NORTH EASTERN REGION OFFICE-JINJA'), ('NORTH EASTERN REGION OFFICE-MBALE', 'NORTH EASTERN REGION OFFICE-MBALE'), ('BOARDROOM', 'BOARDROOM'), ('FINANCIAL ANALYTICS OFFICE', 'FINANCIAL ANALYTICS OFFICE'), ('DIRECTOR ADMIN AND FINANCE', 'DIRECTOR ADMIN AND FINANCE'), ('DIRECTOR PROGRAMS', 'DIRECTOR PROGRAMS'), ('KCCA MANE OFFICE', 'KCCA MANE OFFICE'), ('DEPUTY COUNTRY REPS OFFICE', 'DEPUTY COUNTRY REPS OFFICE'), ('DISC', 'DISC'), ('DIRECTOR WHP', 'DIRECTOR WHP')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='assettb',
            name='PurchaseDate',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 12, 14, 6, 40, 20, 179681, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='AssetType',
            field=models.CharField(blank=True, choices=[('VEHICLE', 'VEHICLE'), ('DESKTOP', 'DESKTOP'), ('LAPTOP', 'LAPTOP'), ('MEDICAL EQUIPMENT', 'MEDICAL EQUIPMENT'), ('TABLET', 'TABLET'), ('PHONE', 'PHONE'), ('COMPUTER ACCESSORY', 'COMPUTER ACCESSORY'), ('NETWORKING EQUIPMENT', 'NETWORKING EQUIPMENT'), ('PROJECTOR', 'PROJECTOR'), ('PRINTER', 'PRINTER'), ('PHOTOCOPIER', 'PHOTOCOPIER'), ('MULTI FUNCTIONAL PRINTER', 'MULTI FUNCTIONAL PRINTER'), ('TABLE', 'TABLE'), ('CHAIR', 'CHAIR'), ('OFFICE ACCESSORY', 'OFFICE ACCESSORY'), ('FAN', 'FAN'), ('INVERTER', 'INVERTER'), ('SERVER', 'SERVER'), ('FIREWALL', 'FIREWALL'), ('SAFE', 'SAFE'), ('SHREDDER', 'SHREDDER'), ('SWITCH', 'SWITCH'), ('BOOKSHELF', 'BOOKSHELF'), ('MICROWAVE', 'MICROWAVE'), ('REFRIGERATOR', 'REFRIGERATOR'), ('NETWORK STORAGE EQUIPMENT', 'NETWORK STORAGE EQUIPMENT'), ('FILING CABINET', 'FILING CABINET'), ('TRASHING MACHINE', 'TRASHING MACHINE'), ('DRAWERS', 'DRAWERS'), ('FIRE EXTINGUISHER', 'FIRE EXTINGUISHER'), ('SHELF', 'SHELF'), ('SOFA CHAIRS', 'SOFA CHAIRS'), ('HIGH BACK ROTATING CHAIR', 'HIGH BACK ROTATING CHAIR'), ('LOW BACK ROTATING CHAIR', 'LOW BACK ROTATING CHAIR'), ('TELEVISION', 'TELEVISION'), ('WATER DISPENSER', 'WATER DISPENSER'), ('TENT', 'TENT'), ('NOT APPLICABLE', 'NOT APPLICABLE')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='Availability',
            field=models.CharField(blank=True, choices=[('AVAILABLE', 'AVAILABLE'), ('ASSIGNED', 'ASSIGNED'), ('TO BE ASSIGNED', 'TO BE ASSIGNED'), ('UNAVAILABLE FOR ASSIGNMENT', 'UNAVAILABLE FOR ASSIGNMENT'), ('MISSING', 'MISSING'), ('LOST', 'LOST'), ('FAULTY-DUE FOR DISPOSAL', 'FAULTY-DUE FOR DISPOSAL'), ('DUE FOR DISPOSAL', 'DUE FOR DISPOSAL'), ('DISPOSED-OF', 'DISPOSED-OF'), ('WRITTEN OFF', 'WRITTEN OFF'), ('FOR INSURANCE REPLACEMENT', 'FOR INSURANCE REPLACEMENT'), ('NOT APPLICABLE ON THIS DEVICE', 'NOT APPLICABLE ON THIS DEVICE')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='Location',
            field=models.CharField(blank=True, choices=[('HEAD OFFICE', 'HEAD OFFICE'), ('CENTRAL REGION OFFICE', 'CENTRAL REGION OFFICE'), ('NORTH EASTERN REGION OFFICE', 'NORTH EASTERN REGION OFFICE'), ('JINJA', 'JINJA'), ('SERVER ROOM', 'SERVER ROOM'), ('FINANCIAL ACCOUNTS', 'FINANCIAL ACCOUNTS'), ("CR'S OFFICE", "CR'S OFFICE"), ('HR OFFICE', 'HR OFFICE'), ('SIL OFFICE', 'SIL OFFICE'), ('SUPPLY CHAIN OFFICE', 'SUPPLY CHAIN OFFICE'), ('IT OFFICE', 'IT OFFICE'), ('PROGRAMS OFFICE', 'PROGRAMS OFFICE'), ('SMD OFFICE', 'SMD OFFICE'), ('HQ-COMMON AREA', 'HQ-COMMON AREA'), ('RECEPTION-HEAD OFFICE', 'RECEPTION-HEAD OFFICE'), ('CAFETERIA', 'CAFETERIA'), ('EASTERN REGION OFFICE', 'EASTERN REGION OFFICE'), ('NORTHERN REGION OFFICE', 'NORTHERN REGION OFFICE'), ('NORTH EASTERN REGION OFFICE-JINJA', 'NORTH EASTERN REGION OFFICE-JINJA'), ('NORTH EASTERN REGION OFFICE-MBALE', 'NORTH EASTERN REGION OFFICE-MBALE'), ('BOARDROOM', 'BOARDROOM'), ('FINANCIAL ANALYTICS OFFICE', 'FINANCIAL ANALYTICS OFFICE'), ('DIRECTOR ADMIN AND FINANCE', 'DIRECTOR ADMIN AND FINANCE'), ('DIRECTOR PROGRAMS', 'DIRECTOR PROGRAMS'), ('KCCA MANE OFFICE', 'KCCA MANE OFFICE'), ('DEPUTY COUNTRY REPS OFFICE', 'DEPUTY COUNTRY REPS OFFICE'), ('DISC', 'DISC'), ('DIRECTOR WHP', 'DIRECTOR WHP')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='LogDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 14, 6, 40, 20, 183149, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='ProjectName',
            field=models.CharField(blank=True, choices=[('WHP', 'WHP'), ('MERCK', 'MERCK'), ('MUM', 'MUM'), ('PFIZER', 'PFIZER'), ('PROGRAM INCOME', 'PROGRAM INCOME'), ('MANE', 'MANE'), ('CMS PROJECT', 'CMS PROJECT'), ('TUNZA', 'TUNZA'), ('COMMERCIAL MARKETS', 'COMMERCIAL MARKETS'), ('CM4FP', 'CM4FP'), ('BERGSTROM FOUNDATION', 'BERGSTROM FOUNDATION'), ('DISC', 'DISC'), ('COMMON COST', 'COMMON COST'), ('HIVST', 'HIVST'), ('CDC', 'CDC'), ('CSF', 'CSF'), ('WIN', 'WIN'), ('NPI', 'NPI')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='PurchaseDate',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 12, 14, 6, 40, 20, 183104, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='disposal',
            name='disposalDate',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 12, 14, 6, 40, 20, 183609, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='verified',
            name='Location',
            field=models.CharField(blank=True, choices=[('HEAD OFFICE', 'HEAD OFFICE'), ('CENTRAL REGION OFFICE', 'CENTRAL REGION OFFICE'), ('NORTH EASTERN REGION OFFICE', 'NORTH EASTERN REGION OFFICE'), ('JINJA', 'JINJA'), ('SERVER ROOM', 'SERVER ROOM'), ('FINANCIAL ACCOUNTS', 'FINANCIAL ACCOUNTS'), ("CR'S OFFICE", "CR'S OFFICE"), ('HR OFFICE', 'HR OFFICE'), ('SIL OFFICE', 'SIL OFFICE'), ('SUPPLY CHAIN OFFICE', 'SUPPLY CHAIN OFFICE'), ('IT OFFICE', 'IT OFFICE'), ('PROGRAMS OFFICE', 'PROGRAMS OFFICE'), ('SMD OFFICE', 'SMD OFFICE'), ('HQ-COMMON AREA', 'HQ-COMMON AREA'), ('RECEPTION-HEAD OFFICE', 'RECEPTION-HEAD OFFICE'), ('CAFETERIA', 'CAFETERIA'), ('EASTERN REGION OFFICE', 'EASTERN REGION OFFICE'), ('NORTHERN REGION OFFICE', 'NORTHERN REGION OFFICE'), ('NORTH EASTERN REGION OFFICE-JINJA', 'NORTH EASTERN REGION OFFICE-JINJA'), ('NORTH EASTERN REGION OFFICE-MBALE', 'NORTH EASTERN REGION OFFICE-MBALE'), ('BOARDROOM', 'BOARDROOM'), ('FINANCIAL ANALYTICS OFFICE', 'FINANCIAL ANALYTICS OFFICE'), ('DIRECTOR ADMIN AND FINANCE', 'DIRECTOR ADMIN AND FINANCE'), ('DIRECTOR PROGRAMS', 'DIRECTOR PROGRAMS'), ('KCCA MANE OFFICE', 'KCCA MANE OFFICE'), ('DEPUTY COUNTRY REPS OFFICE', 'DEPUTY COUNTRY REPS OFFICE'), ('DISC', 'DISC'), ('DIRECTOR WHP', 'DIRECTOR WHP')], max_length=40, null=True),
        ),
    ]
