# Generated by Django 3.2.6 on 2021-12-14 07:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_auto_20211214_0647'),
    ]

    operations = [
        migrations.AddField(
            model_name='assettb',
            name='Ast_Currency',
            field=models.CharField(choices=[('USD', 'USD'), ('UGX', 'UGX')], default='UGX', max_length=100),
        ),
        migrations.AlterField(
            model_name='assetrequests',
            name='Date_Requested',
            field=models.DateField(default=datetime.datetime(2021, 12, 14, 7, 35, 39, 340928, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='assetrequests',
            name='Last_Modified',
            field=models.DateField(default=datetime.datetime(2021, 12, 14, 7, 35, 39, 340960, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='assetrequests',
            name='Request_Modified_Date',
            field=models.DateField(default=datetime.datetime(2021, 12, 14, 7, 35, 39, 340950, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='assettb',
            name='PurchaseDate',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 12, 14, 7, 35, 39, 340462, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='LogDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 14, 7, 35, 39, 343908, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='PurchaseDate',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 12, 14, 7, 35, 39, 343864, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='disposal',
            name='disposalDate',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 12, 14, 7, 35, 39, 344372, tzinfo=utc)),
        ),
    ]
