# Generated by Django 3.2.6 on 2022-04-28 13:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_auto_20211214_0735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetrequests',
            name='Date_Requested',
            field=models.DateField(default=datetime.datetime(2022, 4, 28, 13, 7, 55, 241317, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='assetrequests',
            name='Last_Modified',
            field=models.DateField(default=datetime.datetime(2022, 4, 28, 13, 7, 55, 241350, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='assetrequests',
            name='Request_Modified_Date',
            field=models.DateField(default=datetime.datetime(2022, 4, 28, 13, 7, 55, 241340, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='assettb',
            name='Comments',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='assettb',
            name='Company',
            field=models.CharField(default='351', max_length=10),
        ),
        migrations.AlterField(
            model_name='assettb',
            name='Location',
            field=models.CharField(blank=True, choices=[('HEAD OFFICE', 'HEAD OFFICE'), ('CENTRAL REGION OFFICE', 'CENTRAL REGION OFFICE'), ('NORTH EASTERN REGION OFFICE', 'NORTH EASTERN REGION OFFICE'), ('JINJA', 'JINJA'), ('SERVER ROOM', 'SERVER ROOM'), ('FINANCIAL ACCOUNTS', 'FINANCIAL ACCOUNTS'), ("CR'S OFFICE", "CR'S OFFICE"), ('HR OFFICE', 'HR OFFICE'), ('SIL OFFICE', 'SIL OFFICE'), ('SUPPLY CHAIN OFFICE', 'SUPPLY CHAIN OFFICE'), ('IT OFFICE', 'IT OFFICE'), ('PROGRAMS OFFICE', 'PROGRAMS OFFICE'), ('SMD OFFICE', 'SMD OFFICE'), ('HQ-COMMON AREA', 'HQ-COMMON AREA'), ('RECEPTION-HEAD OFFICE', 'RECEPTION-HEAD OFFICE'), ('CAFETERIA', 'CAFETERIA'), ('EASTERN REGION OFFICE', 'EASTERN REGION OFFICE'), ('NORTHERN REGION OFFICE', 'NORTHERN REGION OFFICE'), ('NORTH EASTERN REGION OFFICE-JINJA', 'NORTH EASTERN REGION OFFICE-JINJA'), ('NORTH EASTERN REGION OFFICE-MBALE', 'NORTH EASTERN REGION OFFICE-MBALE'), ('BOARDROOM', 'BOARDROOM'), ('FINANCIAL ANALYTICS OFFICE', 'FINANCIAL ANALYTICS OFFICE'), ('DIRECTOR ADMIN AND FINANCE', 'DIRECTOR ADMIN AND FINANCE'), ('DIRECTOR PROGRAMS', 'DIRECTOR PROGRAMS'), ('KCCA MANE OFFICE', 'KCCA MANE OFFICE'), ('DEPUTY COUNTRY REPS OFFICE', 'DEPUTY COUNTRY REPS OFFICE'), ('DISC', 'DISC'), ('PACE-HEAD OFFICE', 'PACE-HEAD-OFFICE'), ('PACE-LIRA', 'PACE-LIRA'), ('DIRECTOR WHP', 'DIRECTOR WHP')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='assettb',
            name='PurchaseDate',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 4, 28, 13, 7, 55, 240843, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='Location',
            field=models.CharField(blank=True, choices=[('HEAD OFFICE', 'HEAD OFFICE'), ('CENTRAL REGION OFFICE', 'CENTRAL REGION OFFICE'), ('NORTH EASTERN REGION OFFICE', 'NORTH EASTERN REGION OFFICE'), ('JINJA', 'JINJA'), ('SERVER ROOM', 'SERVER ROOM'), ('FINANCIAL ACCOUNTS', 'FINANCIAL ACCOUNTS'), ("CR'S OFFICE", "CR'S OFFICE"), ('HR OFFICE', 'HR OFFICE'), ('SIL OFFICE', 'SIL OFFICE'), ('SUPPLY CHAIN OFFICE', 'SUPPLY CHAIN OFFICE'), ('IT OFFICE', 'IT OFFICE'), ('PROGRAMS OFFICE', 'PROGRAMS OFFICE'), ('SMD OFFICE', 'SMD OFFICE'), ('HQ-COMMON AREA', 'HQ-COMMON AREA'), ('RECEPTION-HEAD OFFICE', 'RECEPTION-HEAD OFFICE'), ('CAFETERIA', 'CAFETERIA'), ('EASTERN REGION OFFICE', 'EASTERN REGION OFFICE'), ('NORTHERN REGION OFFICE', 'NORTHERN REGION OFFICE'), ('NORTH EASTERN REGION OFFICE-JINJA', 'NORTH EASTERN REGION OFFICE-JINJA'), ('NORTH EASTERN REGION OFFICE-MBALE', 'NORTH EASTERN REGION OFFICE-MBALE'), ('BOARDROOM', 'BOARDROOM'), ('FINANCIAL ANALYTICS OFFICE', 'FINANCIAL ANALYTICS OFFICE'), ('DIRECTOR ADMIN AND FINANCE', 'DIRECTOR ADMIN AND FINANCE'), ('DIRECTOR PROGRAMS', 'DIRECTOR PROGRAMS'), ('KCCA MANE OFFICE', 'KCCA MANE OFFICE'), ('DEPUTY COUNTRY REPS OFFICE', 'DEPUTY COUNTRY REPS OFFICE'), ('DISC', 'DISC'), ('PACE-HEAD OFFICE', 'PACE-HEAD-OFFICE'), ('PACE-LIRA', 'PACE-LIRA'), ('DIRECTOR WHP', 'DIRECTOR WHP')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='LogDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 28, 13, 7, 55, 244273, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='PurchaseDate',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 4, 28, 13, 7, 55, 244229, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='disposal',
            name='disposalDate',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 4, 28, 13, 7, 55, 244724, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='verified',
            name='Location',
            field=models.CharField(blank=True, choices=[('HEAD OFFICE', 'HEAD OFFICE'), ('CENTRAL REGION OFFICE', 'CENTRAL REGION OFFICE'), ('NORTH EASTERN REGION OFFICE', 'NORTH EASTERN REGION OFFICE'), ('JINJA', 'JINJA'), ('SERVER ROOM', 'SERVER ROOM'), ('FINANCIAL ACCOUNTS', 'FINANCIAL ACCOUNTS'), ("CR'S OFFICE", "CR'S OFFICE"), ('HR OFFICE', 'HR OFFICE'), ('SIL OFFICE', 'SIL OFFICE'), ('SUPPLY CHAIN OFFICE', 'SUPPLY CHAIN OFFICE'), ('IT OFFICE', 'IT OFFICE'), ('PROGRAMS OFFICE', 'PROGRAMS OFFICE'), ('SMD OFFICE', 'SMD OFFICE'), ('HQ-COMMON AREA', 'HQ-COMMON AREA'), ('RECEPTION-HEAD OFFICE', 'RECEPTION-HEAD OFFICE'), ('CAFETERIA', 'CAFETERIA'), ('EASTERN REGION OFFICE', 'EASTERN REGION OFFICE'), ('NORTHERN REGION OFFICE', 'NORTHERN REGION OFFICE'), ('NORTH EASTERN REGION OFFICE-JINJA', 'NORTH EASTERN REGION OFFICE-JINJA'), ('NORTH EASTERN REGION OFFICE-MBALE', 'NORTH EASTERN REGION OFFICE-MBALE'), ('BOARDROOM', 'BOARDROOM'), ('FINANCIAL ANALYTICS OFFICE', 'FINANCIAL ANALYTICS OFFICE'), ('DIRECTOR ADMIN AND FINANCE', 'DIRECTOR ADMIN AND FINANCE'), ('DIRECTOR PROGRAMS', 'DIRECTOR PROGRAMS'), ('KCCA MANE OFFICE', 'KCCA MANE OFFICE'), ('DEPUTY COUNTRY REPS OFFICE', 'DEPUTY COUNTRY REPS OFFICE'), ('DISC', 'DISC'), ('PACE-HEAD OFFICE', 'PACE-HEAD-OFFICE'), ('PACE-LIRA', 'PACE-LIRA'), ('DIRECTOR WHP', 'DIRECTOR WHP')], max_length=40, null=True),
        ),
    ]
