# Generated by Django 3.2.6 on 2022-04-29 09:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_auto_20220428_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetrequests',
            name='Date_Requested',
            field=models.DateField(default=datetime.datetime(2022, 4, 29, 9, 37, 32, 195462, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='assetrequests',
            name='Last_Modified',
            field=models.DateField(default=datetime.datetime(2022, 4, 29, 9, 37, 32, 195497, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='assetrequests',
            name='Request_Modified_Date',
            field=models.DateField(default=datetime.datetime(2022, 4, 29, 9, 37, 32, 195486, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='assettb',
            name='PurchaseDate',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 4, 29, 9, 37, 32, 194953, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='ItemCostUGX',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='ItemCostUSD',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='LogDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 29, 9, 37, 32, 198328, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='PurchaseDate',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 4, 29, 9, 37, 32, 198282, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='disposal',
            name='disposalDate',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 4, 29, 9, 37, 32, 198793, tzinfo=utc)),
        ),
    ]
