# Generated by Django 3.2.6 on 2022-04-29 10:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_auto_20220429_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetrequests',
            name='Date_Requested',
            field=models.DateField(default=datetime.datetime(2022, 4, 29, 10, 5, 47, 893034, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='assetrequests',
            name='Last_Modified',
            field=models.DateField(default=datetime.datetime(2022, 4, 29, 10, 5, 47, 893067, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='assetrequests',
            name='Request_Modified_Date',
            field=models.DateField(default=datetime.datetime(2022, 4, 29, 10, 5, 47, 893057, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='assettb',
            name='Blank_Column',
            field=models.CharField(choices=[('None', 'None'), ('Blank', '')], default='0', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assettb',
            name='Company',
            field=models.CharField(default='351', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='assettb',
            name='PurchaseDate',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 4, 29, 10, 5, 47, 892605, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='LogDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 29, 10, 5, 47, 896136, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='PurchaseDate',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 4, 29, 10, 5, 47, 896085, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='disposal',
            name='disposalDate',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 4, 29, 10, 5, 47, 896608, tzinfo=utc)),
        ),
    ]
