# Generated by Django 3.2.6 on 2022-04-29 12:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_auto_20220429_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetrequests',
            name='Date_Requested',
            field=models.DateField(default=datetime.datetime(2022, 4, 29, 12, 45, 0, 158318, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='assetrequests',
            name='Last_Modified',
            field=models.DateField(default=datetime.datetime(2022, 4, 29, 12, 45, 0, 158351, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='assetrequests',
            name='Request_Modified_Date',
            field=models.DateField(default=datetime.datetime(2022, 4, 29, 12, 45, 0, 158340, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='assettb',
            name='Asset_Status',
            field=models.CharField(blank=True, choices=[('VERIFIED', 'VERIFIED'), ('UNVERIFIED', 'UNVERIFIED'), ('AUCTIONED', 'AUCTIONED')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assettb',
            name='Ast_Currency',
            field=models.CharField(blank=True, choices=[('USD', 'USD'), ('UGX', 'UGX')], default='UGX', max_length=100),
        ),
        migrations.AlterField(
            model_name='assettb',
            name='Ast_description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assettb',
            name='Blank_Column',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('Blank', '')], default='0', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assettb',
            name='Project',
            field=models.CharField(blank=True, choices=[('P51PPI', 'P51PPI'), ('6002', '6002'), ('3901', '3901'), ('640051', '640051'), ('4499', '4499'), ('4562PERM', '4562PERM'), ('4482UG', '4482UG'), ('351CCP1', '351CCP1'), ('351ICA', '351ICA'), ('51CCP1', '51CCP1'), ('4115WSHTUNZ', '4115WSHTUNZ'), ('85026', '85026'), ('85032', '85032'), ('051E06', '051E06'), ('4562SA', '4562SA'), ('4562PM', '4562PM'), ('4520', '4520'), ('4336P4HVOP', '4336P4HVOP'), ('4519', '4519'), ('4548', '4548'), ('4385Y3', '4385Y3'), ('051E03', '051E03'), ('4560UG', '4560UG'), ('351E03', '351E03'), ('351CCP2', '351CCP2'), ('4565351', '4565351'), ('4628UG', '4628UG'), ('4621UG', '4621UG'), ('3929BNS', '3929BNS'), ('456951', '456951'), ('3646Y', '3646Y'), ('610051', '610051'), ('630051', '630051'), ('3526', '3526'), ('P3111', 'P3111'), ('P2490', 'P2490'), ('3706SUB', '3706SUB'), ('4254', '4254'), ('683351', '683351'), ('4593NPIPS', '4593NPIPS')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assettb',
            name='Project_Name',
            field=models.CharField(blank=True, choices=[('WHP', 'WHP'), ('MERCK', 'MERCK'), ('MUM', 'MUM'), ('PFIZER', 'PFIZER'), ('PROGRAM INCOME', 'PROGRAM INCOME'), ('MANE', 'MANE'), ('CMS PROJECT', 'CMS PROJECT'), ('TUNZA', 'TUNZA'), ('COMMERCIAL MARKETS', 'COMMERCIAL MARKETS'), ('CM4FP', 'CM4FP'), ('BERGSTROM FOUNDATION', 'BERGSTROM FOUNDATION'), ('DISC', 'DISC'), ('COMMON COST', 'COMMON COST'), ('HIVST', 'HIVST'), ('CDC', 'CDC'), ('CSF', 'CSF'), ('WIN', 'WIN'), ('NPI', 'NPI')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assettb',
            name='PurchaseDate',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 4, 29, 12, 45, 0, 157890, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='LogDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 29, 12, 45, 0, 161519, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='PurchaseDate',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 4, 29, 12, 45, 0, 161467, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='disposal',
            name='disposalDate',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 4, 29, 12, 45, 0, 162022, tzinfo=utc)),
        ),
    ]
