# Generated by Django 3.2.6 on 2022-05-11 07:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_auto_20220429_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assettb',
            name='Blank_Column',
        ),
        migrations.AlterField(
            model_name='assetrequests',
            name='Date_Requested',
            field=models.DateField(default=datetime.datetime(2022, 5, 11, 7, 38, 48, 33065, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='assetrequests',
            name='Device_Type',
            field=models.CharField(blank=True, choices=[('VEHICLE', 'VEHICLE'), ('DESKTOP', 'DESKTOP'), ('LAPTOP', 'LAPTOP'), ('MEDICAL EQUIPMENT', 'MEDICAL EQUIPMENT'), ('TABLET', 'TABLET'), ('PHONE', 'PHONE'), ('COMPUTER ACCESSORY', 'COMPUTER ACCESSORY'), ('NETWORKING EQUIPMENT', 'NETWORKING EQUIPMENT'), ('PROJECTOR', 'PROJECTOR'), ('PRINTER', 'PRINTER'), ('PHOTOCOPIER', 'PHOTOCOPIER'), ('MULTI FUNCTIONAL PRINTER', 'MULTI FUNCTIONAL PRINTER'), ('TABLE', 'TABLE'), ('CHAIR', 'CHAIR'), ('OFFICE ACCESSORY', 'OFFICE ACCESSORY'), ('FAN', 'FAN'), ('INVERTER', 'INVERTER'), ('SERVER', 'SERVER'), ('FIREWALL', 'FIREWALL'), ('SAFE', 'SAFE'), ('SHREDDER', 'SHREDDER'), ('SWITCH', 'SWITCH'), ('BOOKSHELF', 'BOOKSHELF'), ('MICROWAVE', 'MICROWAVE'), ('REFRIGERATOR', 'REFRIGERATOR'), ('NETWORK STORAGE EQUIPMENT', 'NETWORK STORAGE EQUIPMENT'), ('FILING CABINET', 'FILING CABINET'), ('TRASHING MACHINE', 'TRASHING MACHINE'), ('DRAWERS', 'DRAWERS'), ('FIRE EXTINGUISHER', 'FIRE EXTINGUISHER'), ('SHELF', 'SHELF'), ('SOFA CHAIRS', 'SOFA CHAIRS'), ('HIGH BACK ROTATING CHAIR', 'HIGH BACK ROTATING CHAIR'), ('LOW BACK ROTATING CHAIR', 'LOW BACK ROTATING CHAIR'), ('TELEVISION', 'TELEVISION'), ('WATER DISPENSER', 'WATER DISPENSER'), ('TENT', 'TENT'), ('NOT APPLICABLE', 'NOT APPLICABLE'), ('AIR CONDITIONER', 'AIR CONDITIONER')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='assetrequests',
            name='Last_Modified',
            field=models.DateField(default=datetime.datetime(2022, 5, 11, 7, 38, 48, 33098, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='assetrequests',
            name='Request_Modified_Date',
            field=models.DateField(default=datetime.datetime(2022, 5, 11, 7, 38, 48, 33088, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='assettb',
            name='Asset_Type',
            field=models.CharField(blank=True, choices=[('VEHICLE', 'VEHICLE'), ('DESKTOP', 'DESKTOP'), ('LAPTOP', 'LAPTOP'), ('MEDICAL EQUIPMENT', 'MEDICAL EQUIPMENT'), ('TABLET', 'TABLET'), ('PHONE', 'PHONE'), ('COMPUTER ACCESSORY', 'COMPUTER ACCESSORY'), ('NETWORKING EQUIPMENT', 'NETWORKING EQUIPMENT'), ('PROJECTOR', 'PROJECTOR'), ('PRINTER', 'PRINTER'), ('PHOTOCOPIER', 'PHOTOCOPIER'), ('MULTI FUNCTIONAL PRINTER', 'MULTI FUNCTIONAL PRINTER'), ('TABLE', 'TABLE'), ('CHAIR', 'CHAIR'), ('OFFICE ACCESSORY', 'OFFICE ACCESSORY'), ('FAN', 'FAN'), ('INVERTER', 'INVERTER'), ('SERVER', 'SERVER'), ('FIREWALL', 'FIREWALL'), ('SAFE', 'SAFE'), ('SHREDDER', 'SHREDDER'), ('SWITCH', 'SWITCH'), ('BOOKSHELF', 'BOOKSHELF'), ('MICROWAVE', 'MICROWAVE'), ('REFRIGERATOR', 'REFRIGERATOR'), ('NETWORK STORAGE EQUIPMENT', 'NETWORK STORAGE EQUIPMENT'), ('FILING CABINET', 'FILING CABINET'), ('TRASHING MACHINE', 'TRASHING MACHINE'), ('DRAWERS', 'DRAWERS'), ('FIRE EXTINGUISHER', 'FIRE EXTINGUISHER'), ('SHELF', 'SHELF'), ('SOFA CHAIRS', 'SOFA CHAIRS'), ('HIGH BACK ROTATING CHAIR', 'HIGH BACK ROTATING CHAIR'), ('LOW BACK ROTATING CHAIR', 'LOW BACK ROTATING CHAIR'), ('TELEVISION', 'TELEVISION'), ('WATER DISPENSER', 'WATER DISPENSER'), ('TENT', 'TENT'), ('NOT APPLICABLE', 'NOT APPLICABLE'), ('AIR CONDITIONER', 'AIR CONDITIONER')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='assettb',
            name='PurchaseDate',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 5, 11, 7, 38, 48, 32578, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='AssetType',
            field=models.CharField(blank=True, choices=[('VEHICLE', 'VEHICLE'), ('DESKTOP', 'DESKTOP'), ('LAPTOP', 'LAPTOP'), ('MEDICAL EQUIPMENT', 'MEDICAL EQUIPMENT'), ('TABLET', 'TABLET'), ('PHONE', 'PHONE'), ('COMPUTER ACCESSORY', 'COMPUTER ACCESSORY'), ('NETWORKING EQUIPMENT', 'NETWORKING EQUIPMENT'), ('PROJECTOR', 'PROJECTOR'), ('PRINTER', 'PRINTER'), ('PHOTOCOPIER', 'PHOTOCOPIER'), ('MULTI FUNCTIONAL PRINTER', 'MULTI FUNCTIONAL PRINTER'), ('TABLE', 'TABLE'), ('CHAIR', 'CHAIR'), ('OFFICE ACCESSORY', 'OFFICE ACCESSORY'), ('FAN', 'FAN'), ('INVERTER', 'INVERTER'), ('SERVER', 'SERVER'), ('FIREWALL', 'FIREWALL'), ('SAFE', 'SAFE'), ('SHREDDER', 'SHREDDER'), ('SWITCH', 'SWITCH'), ('BOOKSHELF', 'BOOKSHELF'), ('MICROWAVE', 'MICROWAVE'), ('REFRIGERATOR', 'REFRIGERATOR'), ('NETWORK STORAGE EQUIPMENT', 'NETWORK STORAGE EQUIPMENT'), ('FILING CABINET', 'FILING CABINET'), ('TRASHING MACHINE', 'TRASHING MACHINE'), ('DRAWERS', 'DRAWERS'), ('FIRE EXTINGUISHER', 'FIRE EXTINGUISHER'), ('SHELF', 'SHELF'), ('SOFA CHAIRS', 'SOFA CHAIRS'), ('HIGH BACK ROTATING CHAIR', 'HIGH BACK ROTATING CHAIR'), ('LOW BACK ROTATING CHAIR', 'LOW BACK ROTATING CHAIR'), ('TELEVISION', 'TELEVISION'), ('WATER DISPENSER', 'WATER DISPENSER'), ('TENT', 'TENT'), ('NOT APPLICABLE', 'NOT APPLICABLE'), ('AIR CONDITIONER', 'AIR CONDITIONER')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='LogDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 11, 7, 38, 48, 36018, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='PurchaseDate',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 5, 11, 7, 38, 48, 35971, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='disposal',
            name='disposalDate',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 5, 11, 7, 38, 48, 36482, tzinfo=utc)),
        ),
    ]
