# Generated by Django 3.2.6 on 2022-05-11 08:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_auto_20220511_0738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetrequests',
            name='Date_Requested',
            field=models.DateField(default=datetime.datetime(2022, 5, 11, 8, 35, 5, 646044, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='assetrequests',
            name='Last_Modified',
            field=models.DateField(default=datetime.datetime(2022, 5, 11, 8, 35, 5, 646076, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='assetrequests',
            name='Request_Modified_Date',
            field=models.DateField(default=datetime.datetime(2022, 5, 11, 8, 35, 5, 646067, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='assettb',
            name='Project',
            field=models.CharField(blank=True, choices=[('P51PPI', 'P51PPI'), ('6002', '6002'), ('3901', '3901'), ('640051', '640051'), ('4499', '4499'), ('4562PERM', '4562PERM'), ('4482UG', '4482UG'), ('351CCP1', '351CCP1'), ('351ICA', '351ICA'), ('51CCP1', '51CCP1'), ('4115WSHTUNZA', '4115WSHTUNZA'), ('85026', '85026'), ('85032', '85032'), ('051E06', '051E06'), ('4562SA', '4562SA'), ('4562PM', '4562PM'), ('4520', '4520'), ('4336P4HVOP', '4336P4HVOP'), ('4519', '4519'), ('4548', '4548'), ('4385Y3', '4385Y3'), ('051E03', '051E03'), ('4560UG', '4560UG'), ('351E03', '351E03'), ('351CCP2', '351CCP2'), ('4565351', '4565351'), ('4628UG', '4628UG'), ('4621UG', '4621UG'), ('3929BNS', '3929BNS'), ('456951', '456951'), ('3646Y', '3646Y'), ('610051', '610051'), ('630051', '630051'), ('3526', '3526'), ('P3111', 'P3111'), ('P2490', 'P2490'), ('3706SUB', '3706SUB'), ('4254', '4254'), ('683351', '683351'), ('4593NPIPS', '4593NPIPS')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assettb',
            name='PurchaseDate',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 5, 11, 8, 35, 5, 645586, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='LogDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 11, 8, 35, 5, 648933, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='Project',
            field=models.CharField(blank=True, choices=[('P51PPI', 'P51PPI'), ('6002', '6002'), ('3901', '3901'), ('640051', '640051'), ('4499', '4499'), ('4562PERM', '4562PERM'), ('4482UG', '4482UG'), ('351CCP1', '351CCP1'), ('351ICA', '351ICA'), ('51CCP1', '51CCP1'), ('4115WSHTUNZA', '4115WSHTUNZA'), ('85026', '85026'), ('85032', '85032'), ('051E06', '051E06'), ('4562SA', '4562SA'), ('4562PM', '4562PM'), ('4520', '4520'), ('4336P4HVOP', '4336P4HVOP'), ('4519', '4519'), ('4548', '4548'), ('4385Y3', '4385Y3'), ('051E03', '051E03'), ('4560UG', '4560UG'), ('351E03', '351E03'), ('351CCP2', '351CCP2'), ('4565351', '4565351'), ('4628UG', '4628UG'), ('4621UG', '4621UG'), ('3929BNS', '3929BNS'), ('456951', '456951'), ('3646Y', '3646Y'), ('610051', '610051'), ('630051', '630051'), ('3526', '3526'), ('P3111', 'P3111'), ('P2490', 'P2490'), ('3706SUB', '3706SUB'), ('4254', '4254'), ('683351', '683351'), ('4593NPIPS', '4593NPIPS')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='PurchaseDate',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 5, 11, 8, 35, 5, 648886, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='disposal',
            name='disposalDate',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 5, 11, 8, 35, 5, 649404, tzinfo=utc)),
        ),
    ]
