# Generated by Django 3.2.6 on 2022-05-20 05:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0046_auto_20220516_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='staff_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='assetrequests',
            name='Date_Requested',
            field=models.DateField(default=datetime.datetime(2022, 5, 20, 5, 30, 27, 598533, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='assetrequests',
            name='Last_Modified',
            field=models.DateField(default=datetime.datetime(2022, 5, 20, 5, 30, 27, 598569, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='assetrequests',
            name='Request_Modified_Date',
            field=models.DateField(default=datetime.datetime(2022, 5, 20, 5, 30, 27, 598558, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='assettb',
            name='Project_Name',
            field=models.CharField(blank=True, choices=[('WHP', 'WHP'), ('MERCK', 'MERCK'), ('MUM', 'MUM'), ('PFIZER', 'PFIZER'), ('PROGRAM INCOME', 'PROGRAM INCOME'), ('MANE', 'MANE'), ('CMS PROJECT', 'CMS PROJECT'), ('TUNZA', 'TUNZA'), ('COMMERCIAL MARKETS', 'COMMERCIAL MARKETS'), ('CM4FP', 'CM4FP'), ('BERGSTROM FOUNDATION', 'BERGSTROM FOUNDATION'), ('DISC', 'DISC'), ('COMMON COST', 'COMMON COST'), ('HIVST', 'HIVST'), ('CDC', 'CDC'), ('CSF', 'CSF'), ('WIN', 'WIN'), ('NPI', 'NPI'), ('HIVST', 'HIVST'), ('SELFCARE TBG', 'SELFCARE TBG'), ('COVID-19', 'COVID-19'), ('CITY TO CITY', 'CITY TO CITY'), ('DKT', 'DKT'), ('LEAP PROJECT', 'LEAP PROJECT')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assettb',
            name='PurchaseDate',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 5, 20, 5, 30, 27, 597963, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='LogDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 20, 5, 30, 27, 601490, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='ProjectName',
            field=models.CharField(blank=True, choices=[('WHP', 'WHP'), ('MERCK', 'MERCK'), ('MUM', 'MUM'), ('PFIZER', 'PFIZER'), ('PROGRAM INCOME', 'PROGRAM INCOME'), ('MANE', 'MANE'), ('CMS PROJECT', 'CMS PROJECT'), ('TUNZA', 'TUNZA'), ('COMMERCIAL MARKETS', 'COMMERCIAL MARKETS'), ('CM4FP', 'CM4FP'), ('BERGSTROM FOUNDATION', 'BERGSTROM FOUNDATION'), ('DISC', 'DISC'), ('COMMON COST', 'COMMON COST'), ('HIVST', 'HIVST'), ('CDC', 'CDC'), ('CSF', 'CSF'), ('WIN', 'WIN'), ('NPI', 'NPI'), ('HIVST', 'HIVST'), ('SELFCARE TBG', 'SELFCARE TBG'), ('COVID-19', 'COVID-19'), ('CITY TO CITY', 'CITY TO CITY'), ('DKT', 'DKT'), ('LEAP PROJECT', 'LEAP PROJECT')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='PurchaseDate',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 5, 20, 5, 30, 27, 601444, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='disposal',
            name='disposalDate',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 5, 20, 5, 30, 27, 601951, tzinfo=utc)),
        ),
    ]
