# Generated by Django 3.2.6 on 2022-07-12 11:41

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0048_auto_20220520_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='Manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.staff'),
        ),
        migrations.AlterField(
            model_name='assetrequests',
            name='Date_Requested',
            field=models.DateField(default=datetime.datetime(2022, 7, 12, 11, 41, 28, 905058, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='assetrequests',
            name='Last_Modified',
            field=models.DateField(default=datetime.datetime(2022, 7, 12, 11, 41, 28, 905094, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='assetrequests',
            name='Request_Modified_Date',
            field=models.DateField(default=datetime.datetime(2022, 7, 12, 11, 41, 28, 905082, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='assettb',
            name='Asset_Status',
            field=models.CharField(blank=True, choices=[('VERIFIED', 'VERIFIED'), ('UNVERIFIED', 'UNVERIFIED'), ('AUCTIONED', 'AUCTIONED')], default='UNVERIFIED', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assettb',
            name='PurchaseDate',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 7, 12, 11, 41, 28, 904636, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='LogDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 12, 11, 41, 28, 907938, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='PurchaseDate',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 7, 12, 11, 41, 28, 907896, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='disposal',
            name='disposalDate',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 7, 12, 11, 41, 28, 908388, tzinfo=utc)),
        ),
    ]
