# Generated by Django 3.2.6 on 2022-11-16 07:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0051_auto_20220713_1536'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUploads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.FileField(upload_to='documents')),
                ('Date_uploaded', models.DateTimeField(auto_now_add=True)),
                ('Parsed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Staff_Emails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='assetrequests',
            name='AssetManagerApproval',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('User Accepted', 'User Accepted'), ('Returned', 'Returned'), ('In process', 'In Process'), ('Fully Approved', 'Fully Approved')], default='Pending', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='assetrequests',
            name='Date_Requested',
            field=models.DateField(default=datetime.datetime(2022, 11, 16, 7, 31, 43, 134647, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='assetrequests',
            name='Device_Type',
            field=models.CharField(blank=True, choices=[('VEHICLE', 'VEHICLE'), ('DESKTOP', 'DESKTOP'), ('LAPTOP', 'LAPTOP'), ('MEDICAL EQUIPMENT', 'MEDICAL EQUIPMENT'), ('TABLET', 'TABLET'), ('PHONE', 'PHONE'), ('COMPUTER ACCESSORY', 'COMPUTER ACCESSORY'), ('NETWORKING EQUIPMENT', 'NETWORKING EQUIPMENT'), ('PROJECTOR', 'PROJECTOR'), ('PRINTER', 'PRINTER'), ('PHOTOCOPIER', 'PHOTOCOPIER'), ('MULTI FUNCTIONAL PRINTER', 'MULTI FUNCTIONAL PRINTER'), ('TABLE', 'TABLE'), ('CHAIR', 'CHAIR'), ('OFFICE ACCESSORY', 'OFFICE ACCESSORY'), ('FAN', 'FAN'), ('INVERTER', 'INVERTER'), ('SERVER', 'SERVER'), ('FIREWALL', 'FIREWALL'), ('SAFE', 'SAFE'), ('SHREDDER', 'SHREDDER'), ('SWITCH', 'SWITCH'), ('BOOKSHELF', 'BOOKSHELF'), ('MICROWAVE', 'MICROWAVE'), ('REFRIGERATOR', 'REFRIGERATOR'), ('NETWORK STORAGE EQUIPMENT', 'NETWORK STORAGE EQUIPMENT'), ('FILING CABINET', 'FILING CABINET'), ('TRASHING MACHINE', 'TRASHING MACHINE'), ('DRAWERS', 'DRAWERS'), ('FIRE EXTINGUISHER', 'FIRE EXTINGUISHER'), ('SHELF', 'SHELF'), ('SOFA CHAIRS', 'SOFA CHAIRS'), ('HIGH BACK ROTATING CHAIR', 'HIGH BACK ROTATING CHAIR'), ('LOW BACK ROTATING CHAIR', 'LOW BACK ROTATING CHAIR'), ('TELEVISION', 'TELEVISION'), ('WATER DISPENSER', 'WATER DISPENSER'), ('TENT', 'TENT'), ('NOT APPLICABLE', 'NOT APPLICABLE'), ('AIR CONDITIONER', 'AIR CONDITIONER'), ('SERVER RACK', 'SERVER RACK')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='assetrequests',
            name='FinanceManagerApproval',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('User Accepted', 'User Accepted'), ('Returned', 'Returned'), ('In process', 'In Process'), ('Fully Approved', 'Fully Approved')], default='Pending', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='assetrequests',
            name='Last_Modified',
            field=models.DateField(default=datetime.datetime(2022, 11, 16, 7, 31, 43, 134682, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='assetrequests',
            name='Request_Modified_Date',
            field=models.DateField(default=datetime.datetime(2022, 11, 16, 7, 31, 43, 134672, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='assetrequests',
            name='Status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('User Accepted', 'User Accepted'), ('Returned', 'Returned'), ('In process', 'In Process'), ('Fully Approved', 'Fully Approved')], default='Pending', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='assetrequests',
            name='SupervisorApproval',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('User Accepted', 'User Accepted'), ('Returned', 'Returned'), ('In process', 'In Process'), ('Fully Approved', 'Fully Approved')], default='Pending', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='assetrequests',
            name='UserAcceptance',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('User Accepted', 'User Accepted'), ('Returned', 'Returned'), ('In process', 'In Process'), ('Fully Approved', 'Fully Approved')], default='Pending', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='assettb',
            name='Asset_Type',
            field=models.CharField(blank=True, choices=[('VEHICLE', 'VEHICLE'), ('DESKTOP', 'DESKTOP'), ('LAPTOP', 'LAPTOP'), ('MEDICAL EQUIPMENT', 'MEDICAL EQUIPMENT'), ('TABLET', 'TABLET'), ('PHONE', 'PHONE'), ('COMPUTER ACCESSORY', 'COMPUTER ACCESSORY'), ('NETWORKING EQUIPMENT', 'NETWORKING EQUIPMENT'), ('PROJECTOR', 'PROJECTOR'), ('PRINTER', 'PRINTER'), ('PHOTOCOPIER', 'PHOTOCOPIER'), ('MULTI FUNCTIONAL PRINTER', 'MULTI FUNCTIONAL PRINTER'), ('TABLE', 'TABLE'), ('CHAIR', 'CHAIR'), ('OFFICE ACCESSORY', 'OFFICE ACCESSORY'), ('FAN', 'FAN'), ('INVERTER', 'INVERTER'), ('SERVER', 'SERVER'), ('FIREWALL', 'FIREWALL'), ('SAFE', 'SAFE'), ('SHREDDER', 'SHREDDER'), ('SWITCH', 'SWITCH'), ('BOOKSHELF', 'BOOKSHELF'), ('MICROWAVE', 'MICROWAVE'), ('REFRIGERATOR', 'REFRIGERATOR'), ('NETWORK STORAGE EQUIPMENT', 'NETWORK STORAGE EQUIPMENT'), ('FILING CABINET', 'FILING CABINET'), ('TRASHING MACHINE', 'TRASHING MACHINE'), ('DRAWERS', 'DRAWERS'), ('FIRE EXTINGUISHER', 'FIRE EXTINGUISHER'), ('SHELF', 'SHELF'), ('SOFA CHAIRS', 'SOFA CHAIRS'), ('HIGH BACK ROTATING CHAIR', 'HIGH BACK ROTATING CHAIR'), ('LOW BACK ROTATING CHAIR', 'LOW BACK ROTATING CHAIR'), ('TELEVISION', 'TELEVISION'), ('WATER DISPENSER', 'WATER DISPENSER'), ('TENT', 'TENT'), ('NOT APPLICABLE', 'NOT APPLICABLE'), ('AIR CONDITIONER', 'AIR CONDITIONER'), ('SERVER RACK', 'SERVER RACK')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='assettb',
            name='Location',
            field=models.CharField(blank=True, choices=[('HEAD OFFICE', 'HEAD OFFICE'), ('CENTRAL REGION OFFICE', 'CENTRAL REGION OFFICE'), ('NORTH EASTERN REGION OFFICE', 'NORTH EASTERN REGION OFFICE'), ('JINJA', 'JINJA'), ('SERVER ROOM', 'SERVER ROOM'), ('FINANCIAL ACCOUNTS', 'FINANCIAL ACCOUNTS'), ("CR'S OFFICE", "CR'S OFFICE"), ('HR OFFICE', 'HR OFFICE'), ('SIL OFFICE', 'SIL OFFICE'), ('SUPPLY CHAIN OFFICE', 'SUPPLY CHAIN OFFICE'), ('IT OFFICE', 'IT OFFICE'), ('PROGRAMS OFFICE', 'PROGRAMS OFFICE'), ('SMD OFFICE', 'SMD OFFICE'), ('HQ-COMMON AREA', 'HQ-COMMON AREA'), ('RECEPTION-HEAD OFFICE', 'RECEPTION-HEAD OFFICE'), ('CAFETERIA', 'CAFETERIA'), ('EASTERN REGION OFFICE', 'EASTERN REGION OFFICE'), ('NORTHERN REGION OFFICE', 'NORTHERN REGION OFFICE'), ('NORTH EASTERN REGION OFFICE-JINJA', 'NORTH EASTERN REGION OFFICE-JINJA'), ('NORTH EASTERN REGION OFFICE-MBALE', 'NORTH EASTERN REGION OFFICE-MBALE'), ('BOARDROOM', 'BOARDROOM'), ('FINANCIAL ANALYTICS OFFICE', 'FINANCIAL ANALYTICS OFFICE'), ('DIRECTOR ADMIN AND FINANCE', 'DIRECTOR ADMIN AND FINANCE'), ('DIRECTOR PROGRAMS', 'DIRECTOR PROGRAMS'), ('KCCA MANE OFFICE', 'KCCA MANE OFFICE'), ('DEPUTY COUNTRY REPS OFFICE', 'DEPUTY COUNTRY REPS OFFICE'), ('DISC', 'DISC'), ('PACE-HEAD OFFICE', 'PACE-HEAD-OFFICE'), ('PACE-LIRA', 'PACE-LIRA'), ('DIRECTOR WHP', 'DIRECTOR WHP'), ('DISPOSED-OF', 'DISPOSED-OF')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='assettb',
            name='PurchaseDate',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 11, 16, 7, 31, 43, 134175, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='AssetType',
            field=models.CharField(blank=True, choices=[('VEHICLE', 'VEHICLE'), ('DESKTOP', 'DESKTOP'), ('LAPTOP', 'LAPTOP'), ('MEDICAL EQUIPMENT', 'MEDICAL EQUIPMENT'), ('TABLET', 'TABLET'), ('PHONE', 'PHONE'), ('COMPUTER ACCESSORY', 'COMPUTER ACCESSORY'), ('NETWORKING EQUIPMENT', 'NETWORKING EQUIPMENT'), ('PROJECTOR', 'PROJECTOR'), ('PRINTER', 'PRINTER'), ('PHOTOCOPIER', 'PHOTOCOPIER'), ('MULTI FUNCTIONAL PRINTER', 'MULTI FUNCTIONAL PRINTER'), ('TABLE', 'TABLE'), ('CHAIR', 'CHAIR'), ('OFFICE ACCESSORY', 'OFFICE ACCESSORY'), ('FAN', 'FAN'), ('INVERTER', 'INVERTER'), ('SERVER', 'SERVER'), ('FIREWALL', 'FIREWALL'), ('SAFE', 'SAFE'), ('SHREDDER', 'SHREDDER'), ('SWITCH', 'SWITCH'), ('BOOKSHELF', 'BOOKSHELF'), ('MICROWAVE', 'MICROWAVE'), ('REFRIGERATOR', 'REFRIGERATOR'), ('NETWORK STORAGE EQUIPMENT', 'NETWORK STORAGE EQUIPMENT'), ('FILING CABINET', 'FILING CABINET'), ('TRASHING MACHINE', 'TRASHING MACHINE'), ('DRAWERS', 'DRAWERS'), ('FIRE EXTINGUISHER', 'FIRE EXTINGUISHER'), ('SHELF', 'SHELF'), ('SOFA CHAIRS', 'SOFA CHAIRS'), ('HIGH BACK ROTATING CHAIR', 'HIGH BACK ROTATING CHAIR'), ('LOW BACK ROTATING CHAIR', 'LOW BACK ROTATING CHAIR'), ('TELEVISION', 'TELEVISION'), ('WATER DISPENSER', 'WATER DISPENSER'), ('TENT', 'TENT'), ('NOT APPLICABLE', 'NOT APPLICABLE'), ('AIR CONDITIONER', 'AIR CONDITIONER'), ('SERVER RACK', 'SERVER RACK')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='Location',
            field=models.CharField(blank=True, choices=[('HEAD OFFICE', 'HEAD OFFICE'), ('CENTRAL REGION OFFICE', 'CENTRAL REGION OFFICE'), ('NORTH EASTERN REGION OFFICE', 'NORTH EASTERN REGION OFFICE'), ('JINJA', 'JINJA'), ('SERVER ROOM', 'SERVER ROOM'), ('FINANCIAL ACCOUNTS', 'FINANCIAL ACCOUNTS'), ("CR'S OFFICE", "CR'S OFFICE"), ('HR OFFICE', 'HR OFFICE'), ('SIL OFFICE', 'SIL OFFICE'), ('SUPPLY CHAIN OFFICE', 'SUPPLY CHAIN OFFICE'), ('IT OFFICE', 'IT OFFICE'), ('PROGRAMS OFFICE', 'PROGRAMS OFFICE'), ('SMD OFFICE', 'SMD OFFICE'), ('HQ-COMMON AREA', 'HQ-COMMON AREA'), ('RECEPTION-HEAD OFFICE', 'RECEPTION-HEAD OFFICE'), ('CAFETERIA', 'CAFETERIA'), ('EASTERN REGION OFFICE', 'EASTERN REGION OFFICE'), ('NORTHERN REGION OFFICE', 'NORTHERN REGION OFFICE'), ('NORTH EASTERN REGION OFFICE-JINJA', 'NORTH EASTERN REGION OFFICE-JINJA'), ('NORTH EASTERN REGION OFFICE-MBALE', 'NORTH EASTERN REGION OFFICE-MBALE'), ('BOARDROOM', 'BOARDROOM'), ('FINANCIAL ANALYTICS OFFICE', 'FINANCIAL ANALYTICS OFFICE'), ('DIRECTOR ADMIN AND FINANCE', 'DIRECTOR ADMIN AND FINANCE'), ('DIRECTOR PROGRAMS', 'DIRECTOR PROGRAMS'), ('KCCA MANE OFFICE', 'KCCA MANE OFFICE'), ('DEPUTY COUNTRY REPS OFFICE', 'DEPUTY COUNTRY REPS OFFICE'), ('DISC', 'DISC'), ('PACE-HEAD OFFICE', 'PACE-HEAD-OFFICE'), ('PACE-LIRA', 'PACE-LIRA'), ('DIRECTOR WHP', 'DIRECTOR WHP'), ('DISPOSED-OF', 'DISPOSED-OF')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='LogDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 16, 7, 31, 43, 137552, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='PurchaseDate',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 11, 16, 7, 31, 43, 137508, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='deleteassignment',
            name='Response',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('In Process', 'In Process'), ('Fully Approved', 'Fully Approved')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='disposal',
            name='CR_Approval',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('In Process', 'In Process'), ('Fully Approved', 'Fully Approved')], default='Pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='disposal',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='documents'),
        ),
        migrations.AlterField(
            model_name='disposal',
            name='disposalDate',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 11, 16, 7, 31, 43, 138016, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staffrole',
            field=models.CharField(choices=[('User', 'User'), ('Admin', 'Admin'), ('Supervisor', 'Supervisor'), ('Warehouse', 'Warehouse'), ('Supply Chain', 'Supply Chain'), ('SalesApprover', 'SalesApprover'), ('Accountant-AP', 'Accountant-AP'), ('Finance', 'Finance'), ('Assistant Accountant AR', 'Assistant Accountant AR'), ('Systems Administrator', 'Systems Administrator'), ('SIL Officer', 'SIL Officer'), ('Fleet Supervisor', 'Fleet Supervisor'), ('Asset Manager', 'Asset Manager'), ('IT Support Assistant', 'IT Support Assistant'), ('Accountant - Accounts Payables', 'Accountant - Accounts Payables'), ('Advocacy and Communications Officer', 'Advocacy and Communications Officer'), ('Advocacy and Partnerships Coordinator', 'Advocacy and Partnerships Coordinator'), ('Assistant Accountant - Accounts Receivables', 'Assistant Accountant - Accounts Receivables'), ('Assistant Accountant-Treasury', 'Assistant Accountant-Treasury'), ('Country Digital Manager', 'Country Digital Manager'), ('Country Representative', 'Country Representative'), ('CYBER INTER-PERSONAL COMMUNICATION COORDINATOR', 'CYBER INTER-PERSONAL COMMUNICATION COORDINATOR'), ('Deputy Country Representative', 'Deputy Country Representative'), ('Director Programs', 'Director Programs'), ('Director of Finance and Administration', 'Director of Finance and Administration'), ('Digital Community Engagement Officer', 'Digital Community Engagement Officer'), ('Brand Manager', 'Brand Manager'), ('DISC Project Coordinator', 'DISC Project Coordinator'), ('DISC Project Lead', 'DISC Project Lead'), ('District Mobilization Officer - Bergstrom', 'District Mobilization Officer - Bergstrom'), ('District Mobilization Officer- SBC', 'District Mobilization Officer- SBC'), ('Driver', 'Driver'), ('Driver/Logistics Assistant - Bergstrom', 'Driver/Logistics Assistant - Bergstrom'), ('Emergency Medical Services Coordinator', 'Emergency Medical Services Coordinator'), ('Finance and Administration Director', 'Finance and Administration Director'), ('Financial Accounts Manager', 'Financial Accounts Manager'), ('Financial Analytics Manager', 'Financial Analytics Manager'), ('Fleet Supervisor', 'Fleet Supervisor'), ('Head of Regional Operations', 'Head of Regional Operations'), ('Head of Strategic Information and Learning', 'Head of Strategic Information and Learning'), ('Head -Social Behavioral Change', 'Head -Social Behavioral Change'), ('Health Services Coordinator', 'Health Services Coordinator'), ('Human Resources and Administration Assistant', 'Human Resources and Administration Assistant'), ('Human Resources and Administration Coordinator', 'Human Resources and Administration Coordinator'), ('Human Resources and Administration Manager', 'Human Resources and Administration Manager'), ('"Implementation Learning and Adaptation Lead', 'Implementation Learning and Adaptation Lead'), ('Internal Auditor Manager', 'Internal Auditor Manager'), ('Knowledge Management Coordinator', 'Knowledge Management Coordinator'), ('Medical Detailer', 'Medical Detailer'), ('Medical Detailer', 'Medical Detailer'), ('Medical Detailer Supervisor', 'Medical Detailer Supervisor'), ('Monitoring and Evaluation Officer', 'Monitoring and Evaluation Officer'), ('Payroll & Management Accountant', 'Payroll & Management Accountant'), ('Policy and Adaptive Supervisor', 'Policy and Adaptive Supervisor'), ('Procurement Officer', 'Procurement Officer'), ('Project Director - MaNe Kampala Slum project', 'Project Director - MaNe Kampala Slum project'), ('Project Manager-SHIPS', 'Project Manager-SHIPS'), ('Quality Assurance Officer-Bergstrom', 'Quality Assurance Officer-Bergstrom'), ('Research Manager', 'Research Manager'), ('Revolving/Surgical Team Lead', 'Revolving/Surgical Team Lead'), ('Sales and Marketing Manager', 'Sales and Marketing Manager'), ('Sales Coordinator', 'Sales Coordinator'), ('Sales Representative', 'Sales Representative'), ('Sales Representative', 'Sales Representative'), ('SBC Coordinator', 'SBC Coordinator'), ('Senior Technical Advisor', 'Senior Technical Advisor'), ('"Senior Technical Advisor HIV', 'Senior Technical Advisor HIV'), ('"Senior Technical Advisor I,SRH', 'Senior Technical Advisor SRH'), ('Sexual Reproductive Health Officer -Bergstrom', 'Sexual Reproductive Health Officer -Bergstrom'), ('Social Behavioral Change Coordinator', 'Social Behavioral Change Coordinator'), ('Social Behavioral Change Officer', 'Social Behavioral Change Officer'), ('Social Entreprise Lead East Africa', 'Social Entreprise Lead East Africa'), ('Strategic Communications Manager', 'Strategic Communications Manager'), ('Strategic Information and Learning Coordinator', 'Strategic Information and Learning Coordinator'), ('Supply Chain Manager', 'Supply Chain Manager'), ('Systems Administrator', 'Systems Administrator'), ('Team Lead-Bergstrom', 'Team Lead-Bergstrom'), ('Technical Learning and Innovations Manager', 'Technical Learning and Innovations Manager'), ('Temporary Below the Line Activation Assistant', 'Temporary Below the Line Activation Assistant'), ('Temporary Procurement Assistant', 'Temporary Procurement Assistant'), ('Temporary Quality Assurance Officer', 'Temporary Quality Assurance Officer'), ('Temporary Social Behavioral Change Officer', 'Temporary Social Behavioral Change Officer'), ('Assistant Quality Assurance Officer', 'Assistant Quality Assurance Officer'), ('Quality Assurance Officer', 'Quality Assurance Officer'), ('Youth Friendly Services Officer', 'Youth Friendly Services Officer')], max_length=60, null=True),
        ),
    ]
